#!/usr/bin/env python3
import json, collections, sys, os

# ---------------------------------------------------------------------------
# German (informal "du") — the existing, reviewed translation.
# ---------------------------------------------------------------------------
de = {
    "The controller isn't receiving video from this camera. Restarting the camera in UniFi Protect usually fixes this.": "Der Controller empfängt kein Video von dieser Kamera. Ein Neustart der Kamera in UniFi Protect behebt das in der Regel.",
    # Keep-alive settings (were added to the catalog by hand; now sourced here).
    "Keep streams alive": "Streams aktiv halten",
    "Kept-alive streams stay connected but skip video decoding while the panel is closed, cutting CPU use to nearly nothing. The picture catches up instantly on reopen.": "Aktiv gehaltene Streams bleiben verbunden, überspringen aber die Videodekodierung, solange das Panel geschlossen ist – das senkt die CPU-Last auf fast null. Beim Wiederöffnen ist das Bild sofort aktuell.",
    "Off": "Aus",
    "Pause decoding while closed": "Dekodierung bei geschlossenem Fenster pausieren",
    "Streams stay connected for this long after closing, so a quick reopen shows video instantly": "Streams bleiben nach dem Schließen so lange verbunden – öffnest du schnell wieder, ist das Video sofort da",
    "Couldn't register this shortcut — it may be in use by another app.": "Dieses Kürzel konnte nicht registriert werden – möglicherweise wird es von einer anderen App verwendet.",
    "Trusted key": "Vertrauter Schlüssel",
    "New key": "Neuer Schlüssel",
    "The controller is presenting a new certificate. This is expected if you reinstalled or replaced the controller — but if you didn't, it may indicate someone intercepting the connection. Compare the new key with the certificate your controller shows before trusting it.": "Der Controller zeigt ein neues Zertifikat. Das ist zu erwarten, wenn du den Controller neu installiert oder ersetzt hast – falls nicht, kann es aber bedeuten, dass jemand die Verbindung abfängt. Vergleiche den neuen Schlüssel mit dem Zertifikat, das dein Controller anzeigt, bevor du ihm vertraust.",
    "Save Current View as New Profile…": "Aktuelle Ansicht als neues Profil sichern…",
    "Save Current View as New Profile": "Aktuelle Ansicht als neues Profil sichern",
    "Add Camera": "Kamera hinzufügen",
    "Save": "Sichern",
    "Rename Profile…": "Profil umbenennen…",
    "Rename Profile": "Profil umbenennen",
    "Rename": "Umbenennen",
    "Delete Profile": "Profil löschen",
    "Switch layout profile": "Layout-Profil wechseln",
    "Profile name": "Profilname",
    "Default": "Standard",
    "Visibility, size, and order apply to the “%@” profile. Switch profiles from the popover header.": "Sichtbarkeit, Größe und Reihenfolge gelten für das Profil „%@“. Wechsle Profile über die Kopfzeile des Popovers.",
    "Certificate": "Zertifikat",
    "Certificate changed": "Zertifikat geändert",
    "PTZ unavailable — check the username and password in Settings.": "PTZ nicht verfügbar – prüfe Benutzername und Passwort in den Einstellungen.",
    "The controller is presenting a new certificate (key %@…). This is expected if you reinstalled or replaced the controller — but if you didn't, it may indicate someone intercepting the connection. Trust it only if you recognize the change.": "Der Controller zeigt ein neues Zertifikat (Schlüssel %@…). Das ist zu erwarten, wenn du den Controller neu installiert oder ersetzt hast – falls nicht, kann es aber bedeuten, dass jemand die Verbindung abfängt. Vertraue ihm nur, wenn du die Änderung kennst.",
    "The controller's certificate changed. Open Settings to review and trust it.": "Das Zertifikat des Controllers hat sich geändert. Öffne die Einstellungen, um es zu prüfen und ihm zu vertrauen.",
    "Trust new certificate": "Neuem Zertifikat vertrauen",
    "Get update": "Update laden",
    "API Key": "API-Schlüssel",
    "About": "Über",
    "All set": "Alles bereit",
    "App replacement failed: %@": "App-Austausch fehlgeschlagen: %@",
    "Accent": "Akzentfarbe",
    "Appearance": "Darstellung",
    "Auto": "Auto",
    "Automatically start QuickProtect when you log in.": "QuickProtect automatisch starten, wenn du dich anmeldest.",
    "Back": "Zurück",
    "Back to grid (Esc)": "Zurück zum Raster (Esc)",
    "Cameras": "Kameras",
    "Can't reach controller": "Controller nicht erreichbar",
    "Cancel": "Abbrechen",
    "Change": "Ändern",
    "Check for Updates": "Nach Updates suchen",
    "Checking…": "Suche läuft…",
    "Classic API credentials": "Anmeldedaten für klassische API",
    "Clear": "Löschen",
    "Clear search": "Suche löschen",
    "Click": "Klick",
    "Click the aperture icon in your menu bar to open the camera grid, or press your global shortcut.": "Klicke auf das Blendensymbol in der Menüleiste, um das Kameraraster zu öffnen, oder drücke deinen globalen Kurzbefehl.",
    "Connect": "Verbinden",
    "Connect your controller": "Controller verbinden",
    "Connected": "Verbunden",
    "Connected, but no cameras came back. Adopt one in the Protect app, then refresh.": "Verbunden, aber keine Kameras gefunden. Übernimm eine in der Protect-App und aktualisiere dann.",
    "Connecting…": "Verbinde…",
    "Connection": "Verbindung",
    "Continue": "Weiter",
    "Controller": "Controller",
    "Dark": "Dunkel",
    "Disconnected": "Getrennt",
    "Dismiss": "Schließen",
    "Display fullscreen": "Vollbild anzeigen",
    "Display the keyboard-shortcut hints and the on-screen PTZ pad when a camera is in focus.": "Tastaturkurzbefehl-Hinweise und das PTZ-Steuerkreuz anzeigen, wenn eine Kamera in der Großansicht ist.",
    "Double-click": "Doppelklick",
    "Download failed: %@": "Download fehlgeschlagen: %@",
    "Enable": "Aktivieren",
    "Enter your UniFi Protect controller's local IP and an API key from its settings.": "Gib die lokale IP deines UniFi-Protect-Controllers und einen API-Schlüssel aus dessen Einstellungen ein.",
    "Esc": "Esc",
    "Exit / back": "Beenden / Zurück",
    "F  ·  Space": "F  ·  Leertaste",
    "Failed to mount the update DMG": "Update-DMG konnte nicht eingebunden werden",
    "Failed to save download: %@": "Download konnte nicht gespeichert werden: %@",
    "Fill frame": "Bild füllen",
    "Finish": "Fertig",
    "Fit to frame": "Einpassen",
    "Focus camera": "Kamera vergrößern",
    "Focus view": "Großansicht",
    "Fullscreen": "Vollbild",
    "Fullscreen (F)": "Vollbild (F)",
    "General": "Allgemein",
    "Global": "Global",
    "Grid": "Raster",
    "Hide this camera": "Diese Kamera ausblenden",
    "IP Address": "IP-Adresse",
    "Install Update": "Update installieren",
    "Installed": "Installiert",
    "Installing update…": "Update wird installiert…",
    "Integration API key from controller settings": "Integrations-API-Schlüssel aus den Controller-Einstellungen",
    "Invalid IP address or URL.": "Ungültige IP-Adresse oder URL.",
    "Large": "Groß",
    "Last try: %@": "Letzter Versuch: %@",
    "Launch at login": "Beim Anmelden starten",
    "Legal": "Rechtliches",
    "License": "Lizenz",
    "Light": "Hell",
    "Live UniFi Protect feeds, one click from your menu bar.": "Live-UniFi-Protect-Feeds, nur einen Klick von der Menüleiste entfernt.",
    "Local IP of your UniFi Protect controller": "Lokale IP des UniFi-Protect-Controllers",
    "Local admin account on the Protect controller.": "Lokales Admin-Konto auf dem Protect-Controller.",
    "Login failed — check the username and password": "Anmeldung fehlgeschlagen – prüfe Benutzername und Passwort",
    "Login failed — check username and password": "Anmeldung fehlgeschlagen – prüfe Benutzername und Passwort",
    "Medium": "Mittel",
    "Menu-bar status app for UniFi Protect. Live camera feeds, one click away.": "Menüleisten-App für UniFi Protect. Live-Kamerafeeds, nur einen Klick entfernt.",
    "No API key configured. Open Settings.": "Kein API-Schlüssel konfiguriert. Öffne die Einstellungen.",
    "No DMG download URL found": "Keine DMG-Download-URL gefunden",
    "No IP address configured. Open Settings.": "Keine IP-Adresse konfiguriert. Öffne die Einstellungen.",
    "No app bundle found in the DMG": "Kein App-Bundle in der DMG gefunden",
    "No cameras discovered yet. Run Test Connection on the Connection tab.": "Noch keine Kameras gefunden. Führe „Verbindung testen“ im Tab „Verbindung“ aus.",
    "No cameras yet": "Noch keine Kameras",
    "Not Now": "Jetzt nicht",
    "Not configured": "Nicht konfiguriert",
    "Not verified": "Nicht verifiziert",
    "Offline": "Offline",
    "Open Settings": "Einstellungen öffnen",
    "Open in Protect": "In Protect öffnen",
    "PTZ (optional)": "PTZ (optional)",
    "PTZ · ARROW KEYS": "PTZ · PFEILTASTEN",
    "PTZ control (optional)": "PTZ-Steuerung (optional)",
    "PTZ control uses the classic Protect API, which requires a local account. The Integration API (API Key) only exposes preset and patrol endpoints, not free-form movement.": "Die PTZ-Steuerung nutzt die klassische Protect-API, die ein lokales Konto erfordert. Die Integrations-API (API-Schlüssel) bietet nur Endpunkte für Voreinstellungen und Patrouillen, keine freie Bewegung.",
    "Pan & tilt (PTZ)": "Schwenken & Neigen (PTZ)",
    "Pan / tilt": "Schwenken / Neigen",
    "Pan left": "Nach links schwenken",
    "Pan right": "Nach rechts schwenken",
    "Password": "Passwort",
    "Press shortcut…": "Kurzbefehl drücken…",
    "QuickProtect can start automatically when you log in so your cameras are always one click away.": "QuickProtect kann beim Anmelden automatisch starten, damit deine Kameras immer nur einen Klick entfernt sind.",
    "QuickProtect – Settings": "QuickProtect – Einstellungen",
    "Quit QuickProtect": "QuickProtect beenden",
    "RTSP · no media": "RTSP · keine Medien",
    "Reconnect": "Erneut verbinden",
    "Refresh": "Aktualisieren",
    "Refresh cameras": "Kameras aktualisieren",
    "Reset size to Auto": "Größe auf Auto zurücksetzen",
    "Retry": "Wiederholen",
    "Search cameras": "Kameras suchen",
    "Settings": "Einstellungen",
    "Settings…": "Einstellungen…",
    "Shortcuts": "Kurzbefehle",
    "Show or hide the camera grid from anywhere.": "Das Kameraraster von überall ein- oder ausblenden.",
    "Show overlay controls": "Overlay-Steuerung anzeigen",
    "Signed in · PTZ control ready": "Angemeldet · PTZ-Steuerung bereit",
    "Signed in — PTZ control ready": "Angemeldet – PTZ-Steuerung bereit",
    "Size": "Größe",
    "Skip": "Überspringen",
    "Small": "Klein",
    "Source": "Quelle",
    "Start QuickProtect at Login?": "QuickProtect beim Anmelden starten?",
    "Startup": "Start",
    "Step 1 of 3": "Schritt 1 von 3",
    "Step 2 of 3": "Schritt 2 von 3",
    "Step 3 of 3": "Schritt 3 von 3",
    "Stream protocol": "Stream-Protokoll",
    "Stream unavailable": "Stream nicht verfügbar",
    "Test Connection": "Verbindung testen",
    "Theme": "Design",
    "Tilt down": "Nach unten neigen",
    "Tilt up": "Nach oben neigen",
    "To pan and tilt PTZ cameras, QuickProtect needs a local admin account. The Integration API key only exposes preset and patrol endpoints, not free-form movement. You can skip this and add it later in Settings.": "Zum Schwenken und Neigen von PTZ-Kameras benötigt QuickProtect ein lokales Admin-Konto. Der Integrations-API-Schlüssel bietet nur Endpunkte für Voreinstellungen und Patrouillen, keine freie Bewegung. Du kannst diesen Schritt überspringen und ihn später in den Einstellungen hinzufügen.",
    "Toggle QuickProtect": "QuickProtect umschalten",
    "Updates": "Updates",
    "Username": "Benutzername",
    "Version": "Version",
    "View License": "Lizenz anzeigen",
    "View fullscreen": "Vollbild anzeigen",
    "View on GitHub": "Auf GitHub ansehen",
    "View the project source and releases.": "Quellcode und Releases des Projekts ansehen.",
    "Welcome to\nQuickProtect.": "Willkommen bei\nQuickProtect.",
    "Within QuickProtect": "Innerhalb von QuickProtect",
    "You're all set.": "Alles bereit.",
    "Digital zoom": "Digitaler Zoom",
    "Zoom": "Zoom",
    "Zoom (PTZ)": "Zoom (PTZ)",
    "Zoom in (I)": "Heranzoomen (I)",
    "Zoom out (O)": "Herauszoomen (O)",
    "back to popover": "zurück zum Popover",
    "exit fullscreen": "Vollbild beenden",
    "just now": "gerade eben",
    "v%@ available": "v%@ verfügbar",
    "© 2026 Christian Bartels · Released under the MIT License.": "© 2026 Christian Bartels · Veröffentlicht unter der MIT-Lizenz.",
    "⌘+scroll": "⌘+Scrollen",
}

# ---------------------------------------------------------------------------
# French (formal "vous" — macOS norm)
# ---------------------------------------------------------------------------
fr = {
    "The controller isn't receiving video from this camera. Restarting the camera in UniFi Protect usually fixes this.": "Le contrôleur ne reçoit pas de vidéo de cette caméra. Redémarrer la caméra dans UniFi Protect règle généralement le problème.",
    # Keep-alive settings (were added to the catalog by hand; now sourced here).
    "Keep streams alive": "Garder les flux actifs",
    "Kept-alive streams stay connected but skip video decoding while the panel is closed, cutting CPU use to nearly nothing. The picture catches up instantly on reopen.": "Les flux maintenus restent connectés mais sautent le décodage vidéo tant que le panneau est fermé, réduisant l'usage CPU à presque rien. L'image se met à jour instantanément à la réouverture.",
    "Off": "Désactivé",
    "Pause decoding while closed": "Suspendre le décodage quand le panneau est fermé",
    "Streams stay connected for this long after closing, so a quick reopen shows video instantly": "Les flux restent connectés pendant cette durée après la fermeture – la vidéo s'affiche instantanément à la réouverture",
    "Couldn't register this shortcut — it may be in use by another app.": "Impossible d'enregistrer ce raccourci — il est peut-être déjà utilisé par une autre app.",
    "Trusted key": "Clé approuvée",
    "New key": "Nouvelle clé",
    "The controller is presenting a new certificate. This is expected if you reinstalled or replaced the controller — but if you didn't, it may indicate someone intercepting the connection. Compare the new key with the certificate your controller shows before trusting it.": "Le contrôleur présente un nouveau certificat. C'est normal si vous l'avez réinstallé ou remplacé — sinon, cela peut indiquer que quelqu'un intercepte la connexion. Comparez la nouvelle clé avec le certificat affiché par votre contrôleur avant de l'approuver.",
    "Save Current View as New Profile…": "Enregistrer la vue actuelle comme nouveau profil…",
    "Save Current View as New Profile": "Enregistrer la vue actuelle comme nouveau profil",
    "Add Camera": "Ajouter une caméra",
    "Save": "Enregistrer",
    "Rename Profile…": "Renommer le profil…",
    "Rename Profile": "Renommer le profil",
    "Rename": "Renommer",
    "Delete Profile": "Supprimer le profil",
    "Switch layout profile": "Changer de profil de disposition",
    "Profile name": "Nom du profil",
    "Default": "Par défaut",
    "Visibility, size, and order apply to the “%@” profile. Switch profiles from the popover header.": "La visibilité, la taille et l'ordre s'appliquent au profil « %@ ». Changez de profil depuis l'en-tête du popover.",
    "Certificate": "Certificat",
    "Certificate changed": "Certificat modifié",
    "PTZ unavailable — check the username and password in Settings.": "PTZ indisponible — vérifiez le nom d'utilisateur et le mot de passe dans les réglages.",
    "The controller is presenting a new certificate (key %@…). This is expected if you reinstalled or replaced the controller — but if you didn't, it may indicate someone intercepting the connection. Trust it only if you recognize the change.": "Le contrôleur présente un nouveau certificat (clé %@…). C'est normal si vous avez réinstallé ou remplacé le contrôleur — sinon, cela peut indiquer que quelqu'un intercepte la connexion. Ne l'approuvez que si vous reconnaissez ce changement.",
    "The controller's certificate changed. Open Settings to review and trust it.": "Le certificat du contrôleur a changé. Ouvrez les réglages pour l'examiner et l'approuver.",
    "Trust new certificate": "Approuver le nouveau certificat",
    "Get update": "Obtenir la mise à jour",
    "API Key": "Clé API",
    "About": "À propos",
    "All set": "Terminé",
    "App replacement failed: %@": "Échec du remplacement de l'app : %@",
    "Accent": "Accent",
    "Appearance": "Apparence",
    "Auto": "Auto",
    "Automatically start QuickProtect when you log in.": "Démarrer QuickProtect automatiquement à la connexion.",
    "Back": "Retour",
    "Back to grid (Esc)": "Retour à la grille (Échap)",
    "Cameras": "Caméras",
    "Can't reach controller": "Contrôleur injoignable",
    "Cancel": "Annuler",
    "Change": "Modifier",
    "Check for Updates": "Rechercher des mises à jour",
    "Checking…": "Recherche…",
    "Classic API credentials": "Identifiants de l'API classique",
    "Clear": "Effacer",
    "Clear search": "Effacer la recherche",
    "Click": "Clic",
    "Click the aperture icon in your menu bar to open the camera grid, or press your global shortcut.": "Cliquez sur l'icône de diaphragme dans la barre des menus pour ouvrir la grille des caméras, ou utilisez votre raccourci global.",
    "Connect": "Connexion",
    "Connect your controller": "Connectez votre contrôleur",
    "Connected": "Connecté",
    "Connected, but no cameras came back. Adopt one in the Protect app, then refresh.": "Connecté, mais aucune caméra trouvée. Adoptez-en une dans l'app Protect, puis actualisez.",
    "Connecting…": "Connexion en cours…",
    "Connection": "Connexion",
    "Continue": "Continuer",
    "Controller": "Contrôleur",
    "Dark": "Sombre",
    "Disconnected": "Déconnecté",
    "Dismiss": "Fermer",
    "Display fullscreen": "Afficher en plein écran",
    "Display the keyboard-shortcut hints and the on-screen PTZ pad when a camera is in focus.": "Afficher les rappels de raccourcis clavier et le pavé PTZ à l'écran lorsqu'une caméra est en vue agrandie.",
    "Double-click": "Double-clic",
    "Download failed: %@": "Échec du téléchargement : %@",
    "Enable": "Activer",
    "Enter your UniFi Protect controller's local IP and an API key from its settings.": "Saisissez l'IP locale de votre contrôleur UniFi Protect et une clé API depuis ses réglages.",
    "Esc": "Échap",
    "Exit / back": "Quitter / retour",
    "F  ·  Space": "F  ·  Espace",
    "Failed to mount the update DMG": "Impossible de monter le DMG de mise à jour",
    "Failed to save download: %@": "Échec de l'enregistrement du téléchargement : %@",
    "Fill frame": "Remplir le cadre",
    "Finish": "Terminer",
    "Fit to frame": "Ajuster au cadre",
    "Focus camera": "Agrandir la caméra",
    "Focus view": "Vue agrandie",
    "Fullscreen": "Plein écran",
    "Fullscreen (F)": "Plein écran (F)",
    "General": "Général",
    "Global": "Global",
    "Grid": "Grille",
    "Hide this camera": "Masquer cette caméra",
    "IP Address": "Adresse IP",
    "Install Update": "Installer la mise à jour",
    "Installed": "Installée",
    "Installing update…": "Installation de la mise à jour…",
    "Integration API key from controller settings": "Clé de l'API d'intégration depuis les réglages du contrôleur",
    "Invalid IP address or URL.": "Adresse IP ou URL non valide.",
    "Large": "Grand",
    "Last try: %@": "Dernier essai : %@",
    "Launch at login": "Lancer à la connexion",
    "Legal": "Mentions légales",
    "License": "Licence",
    "Light": "Clair",
    "Live UniFi Protect feeds, one click from your menu bar.": "Les flux UniFi Protect en direct, à un clic de votre barre des menus.",
    "Local IP of your UniFi Protect controller": "IP locale de votre contrôleur UniFi Protect",
    "Local admin account on the Protect controller.": "Compte administrateur local sur le contrôleur Protect.",
    "Login failed — check the username and password": "Échec de la connexion — vérifiez le nom d'utilisateur et le mot de passe",
    "Login failed — check username and password": "Échec de la connexion — vérifiez le nom d'utilisateur et le mot de passe",
    "Medium": "Moyen",
    "Menu-bar status app for UniFi Protect. Live camera feeds, one click away.": "App de barre des menus pour UniFi Protect. Les flux des caméras en direct, à portée de clic.",
    "No API key configured. Open Settings.": "Aucune clé API configurée. Ouvrez les réglages.",
    "No DMG download URL found": "Aucune URL de téléchargement DMG trouvée",
    "No IP address configured. Open Settings.": "Aucune adresse IP configurée. Ouvrez les réglages.",
    "No app bundle found in the DMG": "Aucune app trouvée dans le DMG",
    "No cameras discovered yet. Run Test Connection on the Connection tab.": "Aucune caméra détectée pour le moment. Lancez « Tester la connexion » dans l'onglet Connexion.",
    "No cameras yet": "Aucune caméra pour l'instant",
    "Not Now": "Plus tard",
    "Not configured": "Non configuré",
    "Not verified": "Non vérifié",
    "Offline": "Hors ligne",
    "Open Settings": "Ouvrir les réglages",
    "Open in Protect": "Ouvrir dans Protect",
    "PTZ (optional)": "PTZ (facultatif)",
    "PTZ · ARROW KEYS": "PTZ · TOUCHES FLÉCHÉES",
    "PTZ control (optional)": "Contrôle PTZ (facultatif)",
    "PTZ control uses the classic Protect API, which requires a local account. The Integration API (API Key) only exposes preset and patrol endpoints, not free-form movement.": "Le contrôle PTZ utilise l'API Protect classique, qui nécessite un compte local. L'API d'intégration (clé API) n'expose que les points de terminaison de préréglages et de patrouilles, pas le mouvement libre.",
    "Pan & tilt (PTZ)": "Panoramique et inclinaison (PTZ)",
    "Pan / tilt": "Panoramique / inclinaison",
    "Pan left": "Panoramique à gauche",
    "Pan right": "Panoramique à droite",
    "Password": "Mot de passe",
    "Press shortcut…": "Appuyez sur le raccourci…",
    "QuickProtect can start automatically when you log in so your cameras are always one click away.": "QuickProtect peut démarrer automatiquement à la connexion pour que vos caméras soient toujours à un clic.",
    "QuickProtect – Settings": "QuickProtect – Réglages",
    "Quit QuickProtect": "Quitter QuickProtect",
    "RTSP · no media": "RTSP · aucun média",
    "Reconnect": "Reconnecter",
    "Refresh": "Actualiser",
    "Refresh cameras": "Actualiser les caméras",
    "Reset size to Auto": "Réinitialiser la taille sur Auto",
    "Retry": "Réessayer",
    "Search cameras": "Rechercher des caméras",
    "Settings": "Réglages",
    "Settings…": "Réglages…",
    "Shortcuts": "Raccourcis",
    "Show or hide the camera grid from anywhere.": "Affichez ou masquez la grille des caméras depuis n'importe où.",
    "Show overlay controls": "Afficher les commandes en surimpression",
    "Signed in · PTZ control ready": "Connecté · contrôle PTZ prêt",
    "Signed in — PTZ control ready": "Connecté — contrôle PTZ prêt",
    "Size": "Taille",
    "Skip": "Ignorer",
    "Small": "Petit",
    "Source": "Code source",
    "Start QuickProtect at Login?": "Démarrer QuickProtect à la connexion ?",
    "Startup": "Démarrage",
    "Step 1 of 3": "Étape 1 sur 3",
    "Step 2 of 3": "Étape 2 sur 3",
    "Step 3 of 3": "Étape 3 sur 3",
    "Stream protocol": "Protocole de flux",
    "Stream unavailable": "Flux indisponible",
    "Test Connection": "Tester la connexion",
    "Theme": "Thème",
    "Tilt down": "Incliner vers le bas",
    "Tilt up": "Incliner vers le haut",
    "To pan and tilt PTZ cameras, QuickProtect needs a local admin account. The Integration API key only exposes preset and patrol endpoints, not free-form movement. You can skip this and add it later in Settings.": "Pour effectuer un panoramique et incliner les caméras PTZ, QuickProtect a besoin d'un compte administrateur local. La clé de l'API d'intégration n'expose que les points de terminaison de préréglages et de patrouilles, pas le mouvement libre. Vous pouvez ignorer cette étape et l'ajouter plus tard dans les réglages.",
    "Toggle QuickProtect": "Afficher/masquer QuickProtect",
    "Updates": "Mises à jour",
    "Username": "Nom d'utilisateur",
    "Version": "Version",
    "View License": "Voir la licence",
    "View fullscreen": "Afficher en plein écran",
    "View on GitHub": "Voir sur GitHub",
    "View the project source and releases.": "Voir le code source du projet et les versions.",
    "Welcome to\nQuickProtect.": "Bienvenue dans\nQuickProtect.",
    "Within QuickProtect": "Dans QuickProtect",
    "You're all set.": "Tout est prêt.",
    "Digital zoom": "Zoom numérique",
    "Zoom": "Zoom",
    "Zoom (PTZ)": "Zoom (PTZ)",
    "Zoom in (I)": "Zoom avant (I)",
    "Zoom out (O)": "Zoom arrière (O)",
    "back to popover": "retour à la fenêtre",
    "exit fullscreen": "quitter le plein écran",
    "just now": "à l'instant",
    "v%@ available": "v%@ disponible",
    "© 2026 Christian Bartels · Released under the MIT License.": "© 2026 Christian Bartels · Distribué sous licence MIT.",
    "⌘+scroll": "⌘+défilement",
}

# ---------------------------------------------------------------------------
# Spanish (informal "tú")
# ---------------------------------------------------------------------------
es = {
    "The controller isn't receiving video from this camera. Restarting the camera in UniFi Protect usually fixes this.": "El controlador no recibe vídeo de esta cámara. Reiniciar la cámara en UniFi Protect suele solucionarlo.",
    # Keep-alive settings (were added to the catalog by hand; now sourced here).
    "Keep streams alive": "Mantener streams activos",
    "Kept-alive streams stay connected but skip video decoding while the panel is closed, cutting CPU use to nearly nothing. The picture catches up instantly on reopen.": "Los streams mantenidos siguen conectados pero omiten la decodificación de vídeo mientras el panel está cerrado, reduciendo el uso de CPU casi a cero. La imagen se actualiza al instante al reabrir.",
    "Off": "Desactivado",
    "Pause decoding while closed": "Pausar la decodificación con el panel cerrado",
    "Streams stay connected for this long after closing, so a quick reopen shows video instantly": "Los streams permanecen conectados durante este tiempo tras cerrar, así el vídeo aparece al instante al reabrir",
    "Couldn't register this shortcut — it may be in use by another app.": "No se pudo registrar este atajo: puede que otra app ya lo esté usando.",
    "Trusted key": "Clave de confianza",
    "New key": "Clave nueva",
    "The controller is presenting a new certificate. This is expected if you reinstalled or replaced the controller — but if you didn't, it may indicate someone intercepting the connection. Compare the new key with the certificate your controller shows before trusting it.": "El controlador presenta un certificado nuevo. Es normal si lo reinstalaste o lo sustituiste; si no, podría indicar que alguien está interceptando la conexión. Compara la clave nueva con el certificado que muestra tu controlador antes de confiar en ella.",
    "Save Current View as New Profile…": "Guardar vista actual como nuevo perfil…",
    "Save Current View as New Profile": "Guardar vista actual como nuevo perfil",
    "Add Camera": "Añadir cámara",
    "Save": "Guardar",
    "Rename Profile…": "Cambiar nombre del perfil…",
    "Rename Profile": "Cambiar nombre del perfil",
    "Rename": "Cambiar nombre",
    "Delete Profile": "Eliminar perfil",
    "Switch layout profile": "Cambiar de perfil de diseño",
    "Profile name": "Nombre del perfil",
    "Default": "Predeterminado",
    "Visibility, size, and order apply to the “%@” profile. Switch profiles from the popover header.": "La visibilidad, el tamaño y el orden se aplican al perfil «%@». Cambia de perfil desde la cabecera del popover.",
    "Certificate": "Certificado",
    "Certificate changed": "Certificado cambiado",
    "PTZ unavailable — check the username and password in Settings.": "PTZ no disponible — comprueba el usuario y la contraseña en los ajustes.",
    "The controller is presenting a new certificate (key %@…). This is expected if you reinstalled or replaced the controller — but if you didn't, it may indicate someone intercepting the connection. Trust it only if you recognize the change.": "El controlador presenta un certificado nuevo (clave %@…). Es lo esperado si reinstalaste o reemplazaste el controlador, pero si no, podría indicar que alguien está interceptando la conexión. Confía en él solo si reconoces el cambio.",
    "The controller's certificate changed. Open Settings to review and trust it.": "El certificado del controlador cambió. Abre los ajustes para revisarlo y confiar en él.",
    "Trust new certificate": "Confiar en el nuevo certificado",
    "Get update": "Obtener actualización",
    "API Key": "Clave API",
    "About": "Acerca de",
    "All set": "Listo",
    "App replacement failed: %@": "Error al reemplazar la app: %@",
    "Accent": "Acento",
    "Appearance": "Apariencia",
    "Auto": "Auto",
    "Automatically start QuickProtect when you log in.": "Iniciar QuickProtect automáticamente al iniciar sesión.",
    "Back": "Atrás",
    "Back to grid (Esc)": "Volver a la cuadrícula (Esc)",
    "Cameras": "Cámaras",
    "Can't reach controller": "No se puede conectar con el controlador",
    "Cancel": "Cancelar",
    "Change": "Cambiar",
    "Check for Updates": "Buscar actualizaciones",
    "Checking…": "Buscando…",
    "Classic API credentials": "Credenciales de la API clásica",
    "Clear": "Borrar",
    "Clear search": "Borrar búsqueda",
    "Click": "Clic",
    "Click the aperture icon in your menu bar to open the camera grid, or press your global shortcut.": "Haz clic en el icono de apertura en la barra de menús para abrir la cuadrícula de cámaras, o pulsa tu atajo global.",
    "Connect": "Conectar",
    "Connect your controller": "Conecta tu controlador",
    "Connected": "Conectado",
    "Connected, but no cameras came back. Adopt one in the Protect app, then refresh.": "Conectado, pero no se encontraron cámaras. Adopta una en la app Protect y luego actualiza.",
    "Connecting…": "Conectando…",
    "Connection": "Conexión",
    "Continue": "Continuar",
    "Controller": "Controlador",
    "Dark": "Oscuro",
    "Disconnected": "Desconectado",
    "Dismiss": "Cerrar",
    "Display fullscreen": "Mostrar en pantalla completa",
    "Display the keyboard-shortcut hints and the on-screen PTZ pad when a camera is in focus.": "Mostrar las indicaciones de atajos de teclado y el panel PTZ en pantalla cuando una cámara está en vista ampliada.",
    "Double-click": "Doble clic",
    "Download failed: %@": "Error en la descarga: %@",
    "Enable": "Activar",
    "Enter your UniFi Protect controller's local IP and an API key from its settings.": "Introduce la IP local de tu controlador UniFi Protect y una clave API desde sus ajustes.",
    "Esc": "Esc",
    "Exit / back": "Salir / atrás",
    "F  ·  Space": "F  ·  Espacio",
    "Failed to mount the update DMG": "No se pudo montar el DMG de actualización",
    "Failed to save download: %@": "No se pudo guardar la descarga: %@",
    "Fill frame": "Llenar el cuadro",
    "Finish": "Finalizar",
    "Fit to frame": "Ajustar al cuadro",
    "Focus camera": "Ampliar cámara",
    "Focus view": "Vista ampliada",
    "Fullscreen": "Pantalla completa",
    "Fullscreen (F)": "Pantalla completa (F)",
    "General": "General",
    "Global": "Global",
    "Grid": "Cuadrícula",
    "Hide this camera": "Ocultar esta cámara",
    "IP Address": "Dirección IP",
    "Install Update": "Instalar actualización",
    "Installed": "Instalada",
    "Installing update…": "Instalando actualización…",
    "Integration API key from controller settings": "Clave de la API de integración desde los ajustes del controlador",
    "Invalid IP address or URL.": "Dirección IP o URL no válida.",
    "Large": "Grande",
    "Last try: %@": "Último intento: %@",
    "Launch at login": "Abrir al iniciar sesión",
    "Legal": "Legal",
    "License": "Licencia",
    "Light": "Claro",
    "Live UniFi Protect feeds, one click from your menu bar.": "Transmisiones UniFi Protect en directo, a un clic desde tu barra de menús.",
    "Local IP of your UniFi Protect controller": "IP local de tu controlador UniFi Protect",
    "Local admin account on the Protect controller.": "Cuenta de administrador local en el controlador Protect.",
    "Login failed — check the username and password": "Error de inicio de sesión — comprueba el usuario y la contraseña",
    "Login failed — check username and password": "Error de inicio de sesión — comprueba el usuario y la contraseña",
    "Medium": "Mediano",
    "Menu-bar status app for UniFi Protect. Live camera feeds, one click away.": "App de barra de menús para UniFi Protect. Transmisiones de cámaras en directo, a un solo clic.",
    "No API key configured. Open Settings.": "No hay clave API configurada. Abre los ajustes.",
    "No DMG download URL found": "No se encontró ninguna URL de descarga del DMG",
    "No IP address configured. Open Settings.": "No hay dirección IP configurada. Abre los ajustes.",
    "No app bundle found in the DMG": "No se encontró ninguna app en el DMG",
    "No cameras discovered yet. Run Test Connection on the Connection tab.": "Aún no se han detectado cámaras. Ejecuta «Probar conexión» en la pestaña Conexión.",
    "No cameras yet": "Aún no hay cámaras",
    "Not Now": "Ahora no",
    "Not configured": "Sin configurar",
    "Not verified": "Sin verificar",
    "Offline": "Sin conexión",
    "Open Settings": "Abrir ajustes",
    "Open in Protect": "Abrir en Protect",
    "PTZ (optional)": "PTZ (opcional)",
    "PTZ · ARROW KEYS": "PTZ · TECLAS DE FLECHA",
    "PTZ control (optional)": "Control PTZ (opcional)",
    "PTZ control uses the classic Protect API, which requires a local account. The Integration API (API Key) only exposes preset and patrol endpoints, not free-form movement.": "El control PTZ usa la API clásica de Protect, que requiere una cuenta local. La API de integración (clave API) solo expone endpoints de preajustes y patrullas, no el movimiento libre.",
    "Pan & tilt (PTZ)": "Giro e inclinación (PTZ)",
    "Pan / tilt": "Giro / inclinación",
    "Pan left": "Girar a la izquierda",
    "Pan right": "Girar a la derecha",
    "Password": "Contraseña",
    "Press shortcut…": "Pulsa el atajo…",
    "QuickProtect can start automatically when you log in so your cameras are always one click away.": "QuickProtect puede iniciarse automáticamente al iniciar sesión para que tus cámaras estén siempre a un clic.",
    "QuickProtect – Settings": "QuickProtect – Ajustes",
    "Quit QuickProtect": "Salir de QuickProtect",
    "RTSP · no media": "RTSP · sin contenido",
    "Reconnect": "Reconectar",
    "Refresh": "Actualizar",
    "Refresh cameras": "Actualizar cámaras",
    "Reset size to Auto": "Restablecer tamaño a Auto",
    "Retry": "Reintentar",
    "Search cameras": "Buscar cámaras",
    "Settings": "Ajustes",
    "Settings…": "Ajustes…",
    "Shortcuts": "Atajos",
    "Show or hide the camera grid from anywhere.": "Muestra u oculta la cuadrícula de cámaras desde cualquier lugar.",
    "Show overlay controls": "Mostrar controles superpuestos",
    "Signed in · PTZ control ready": "Sesión iniciada · control PTZ listo",
    "Signed in — PTZ control ready": "Sesión iniciada — control PTZ listo",
    "Size": "Tamaño",
    "Skip": "Omitir",
    "Small": "Pequeño",
    "Source": "Código fuente",
    "Start QuickProtect at Login?": "¿Iniciar QuickProtect al iniciar sesión?",
    "Startup": "Inicio",
    "Step 1 of 3": "Paso 1 de 3",
    "Step 2 of 3": "Paso 2 de 3",
    "Step 3 of 3": "Paso 3 de 3",
    "Stream protocol": "Protocolo de transmisión",
    "Stream unavailable": "Transmisión no disponible",
    "Test Connection": "Probar conexión",
    "Theme": "Tema",
    "Tilt down": "Inclinar hacia abajo",
    "Tilt up": "Inclinar hacia arriba",
    "To pan and tilt PTZ cameras, QuickProtect needs a local admin account. The Integration API key only exposes preset and patrol endpoints, not free-form movement. You can skip this and add it later in Settings.": "Para girar e inclinar las cámaras PTZ, QuickProtect necesita una cuenta de administrador local. La clave de la API de integración solo expone endpoints de preajustes y patrullas, no el movimiento libre. Puedes omitir esto y añadirlo más tarde en los ajustes.",
    "Toggle QuickProtect": "Mostrar/ocultar QuickProtect",
    "Updates": "Actualizaciones",
    "Username": "Usuario",
    "Version": "Versión",
    "View License": "Ver licencia",
    "View fullscreen": "Ver en pantalla completa",
    "View on GitHub": "Ver en GitHub",
    "View the project source and releases.": "Ver el código fuente del proyecto y las versiones.",
    "Welcome to\nQuickProtect.": "Te damos la bienvenida a\nQuickProtect.",
    "Within QuickProtect": "Dentro de QuickProtect",
    "You're all set.": "Todo listo.",
    "Digital zoom": "Zoom digital",
    "Zoom": "Zoom",
    "Zoom (PTZ)": "Zoom (PTZ)",
    "Zoom in (I)": "Acercar (I)",
    "Zoom out (O)": "Alejar (O)",
    "back to popover": "volver a la ventana",
    "exit fullscreen": "salir de pantalla completa",
    "just now": "ahora mismo",
    "v%@ available": "v%@ disponible",
    "© 2026 Christian Bartels · Released under the MIT License.": "© 2026 Christian Bartels · Publicado bajo la licencia MIT.",
    "⌘+scroll": "⌘+desplazamiento",
}

# ---------------------------------------------------------------------------
# Dutch (informal "je")
# ---------------------------------------------------------------------------
nl = {
    "The controller isn't receiving video from this camera. Restarting the camera in UniFi Protect usually fixes this.": "De controller ontvangt geen video van deze camera. De camera opnieuw starten in UniFi Protect lost dit meestal op.",
    # Keep-alive settings (were added to the catalog by hand; now sourced here).
    "Keep streams alive": "Streams actief houden",
    "Kept-alive streams stay connected but skip video decoding while the panel is closed, cutting CPU use to nearly nothing. The picture catches up instantly on reopen.": "Actief gehouden streams blijven verbonden maar slaan videodecodering over zolang het paneel gesloten is, waardoor het CPU-gebruik vrijwel nul wordt. Het beeld is direct actueel bij opnieuw openen.",
    "Off": "Uit",
    "Pause decoding while closed": "Decoderen pauzeren terwijl gesloten",
    "Streams stay connected for this long after closing, so a quick reopen shows video instantly": "Streams blijven na het sluiten zo lang verbonden, zodat de video direct terug is bij opnieuw openen",
    "Couldn't register this shortcut — it may be in use by another app.": "Deze sneltoets kon niet worden geregistreerd – mogelijk gebruikt een andere app hem al.",
    "Trusted key": "Vertrouwde sleutel",
    "New key": "Nieuwe sleutel",
    "The controller is presenting a new certificate. This is expected if you reinstalled or replaced the controller — but if you didn't, it may indicate someone intercepting the connection. Compare the new key with the certificate your controller shows before trusting it.": "De controller toont een nieuw certificaat. Dat is te verwachten als je de controller opnieuw hebt geïnstalleerd of vervangen – zo niet, dan kan het betekenen dat iemand de verbinding onderschept. Vergelijk de nieuwe sleutel met het certificaat dat je controller toont voordat je hem vertrouwt.",
    "Save Current View as New Profile…": "Huidige weergave als nieuw profiel bewaren…",
    "Save Current View as New Profile": "Huidige weergave als nieuw profiel bewaren",
    "Add Camera": "Camera toevoegen",
    "Save": "Bewaar",
    "Rename Profile…": "Profiel hernoemen…",
    "Rename Profile": "Profiel hernoemen",
    "Rename": "Hernoem",
    "Delete Profile": "Profiel verwijderen",
    "Switch layout profile": "Lay-outprofiel wisselen",
    "Profile name": "Profielnaam",
    "Default": "Standaard",
    "Visibility, size, and order apply to the “%@” profile. Switch profiles from the popover header.": "Zichtbaarheid, grootte en volgorde gelden voor het profiel ‘%@’. Wissel van profiel via de kop van de popover.",
    "Certificate": "Certificaat",
    "Certificate changed": "Certificaat gewijzigd",
    "PTZ unavailable — check the username and password in Settings.": "PTZ niet beschikbaar — controleer gebruikersnaam en wachtwoord in de instellingen.",
    "The controller is presenting a new certificate (key %@…). This is expected if you reinstalled or replaced the controller — but if you didn't, it may indicate someone intercepting the connection. Trust it only if you recognize the change.": "De controller presenteert een nieuw certificaat (sleutel %@…). Dat is te verwachten als je de controller opnieuw hebt geïnstalleerd of vervangen — zo niet, dan kan het betekenen dat iemand de verbinding onderschept. Vertrouw het alleen als je de wijziging herkent.",
    "The controller's certificate changed. Open Settings to review and trust it.": "Het certificaat van de controller is gewijzigd. Open de instellingen om het te controleren en te vertrouwen.",
    "Trust new certificate": "Nieuw certificaat vertrouwen",
    "Get update": "Update ophalen",
    "API Key": "API-sleutel",
    "About": "Over",
    "All set": "Klaar",
    "App replacement failed: %@": "Vervangen van app mislukt: %@",
    "Accent": "Accent",
    "Appearance": "Weergave",
    "Auto": "Auto",
    "Automatically start QuickProtect when you log in.": "Start QuickProtect automatisch wanneer je inlogt.",
    "Back": "Terug",
    "Back to grid (Esc)": "Terug naar raster (Esc)",
    "Cameras": "Camera's",
    "Can't reach controller": "Controller niet bereikbaar",
    "Cancel": "Annuleer",
    "Change": "Wijzig",
    "Check for Updates": "Zoek naar updates",
    "Checking…": "Bezig met zoeken…",
    "Classic API credentials": "Inloggegevens klassieke API",
    "Clear": "Wis",
    "Clear search": "Zoekopdracht wissen",
    "Click": "Klik",
    "Click the aperture icon in your menu bar to open the camera grid, or press your global shortcut.": "Klik op het diafragmasymbool in de menubalk om het cameraraster te openen, of gebruik je globale sneltoets.",
    "Connect": "Verbinden",
    "Connect your controller": "Verbind je controller",
    "Connected": "Verbonden",
    "Connected, but no cameras came back. Adopt one in the Protect app, then refresh.": "Verbonden, maar geen camera's gevonden. Adopteer er een in de Protect-app en vernieuw daarna.",
    "Connecting…": "Bezig met verbinden…",
    "Connection": "Verbinding",
    "Continue": "Ga door",
    "Controller": "Controller",
    "Dark": "Donker",
    "Disconnected": "Verbroken",
    "Dismiss": "Sluit",
    "Display fullscreen": "Toon op volledig scherm",
    "Display the keyboard-shortcut hints and the on-screen PTZ pad when a camera is in focus.": "Toon de sneltoetshints en het PTZ-bedieningspaneel op het scherm wanneer een camera vergroot is.",
    "Double-click": "Dubbelklik",
    "Download failed: %@": "Download mislukt: %@",
    "Enable": "Inschakelen",
    "Enter your UniFi Protect controller's local IP and an API key from its settings.": "Voer het lokale IP-adres van je UniFi Protect-controller en een API-sleutel uit de instellingen in.",
    "Esc": "Esc",
    "Exit / back": "Sluiten / terug",
    "F  ·  Space": "F  ·  Spatie",
    "Failed to mount the update DMG": "Kan de update-DMG niet koppelen",
    "Failed to save download: %@": "Kan download niet opslaan: %@",
    "Fill frame": "Beeld vullen",
    "Finish": "Voltooi",
    "Fit to frame": "Passend maken",
    "Focus camera": "Camera vergroten",
    "Focus view": "Vergrote weergave",
    "Fullscreen": "Volledig scherm",
    "Fullscreen (F)": "Volledig scherm (F)",
    "General": "Algemeen",
    "Global": "Globaal",
    "Grid": "Raster",
    "Hide this camera": "Verberg deze camera",
    "IP Address": "IP-adres",
    "Install Update": "Installeer update",
    "Installed": "Geïnstalleerd",
    "Installing update…": "Update wordt geïnstalleerd…",
    "Integration API key from controller settings": "Integratie-API-sleutel uit de controllerinstellingen",
    "Invalid IP address or URL.": "Ongeldig IP-adres of URL.",
    "Large": "Groot",
    "Last try: %@": "Laatste poging: %@",
    "Launch at login": "Start bij inloggen",
    "Legal": "Juridisch",
    "License": "Licentie",
    "Light": "Licht",
    "Live UniFi Protect feeds, one click from your menu bar.": "Live UniFi Protect-feeds, één klik vanaf je menubalk.",
    "Local IP of your UniFi Protect controller": "Lokaal IP-adres van je UniFi Protect-controller",
    "Local admin account on the Protect controller.": "Lokaal beheerdersaccount op de Protect-controller.",
    "Login failed — check the username and password": "Inloggen mislukt — controleer gebruikersnaam en wachtwoord",
    "Login failed — check username and password": "Inloggen mislukt — controleer gebruikersnaam en wachtwoord",
    "Medium": "Gemiddeld",
    "Menu-bar status app for UniFi Protect. Live camera feeds, one click away.": "Menubalk-app voor UniFi Protect. Live camerabeelden, één klik verwijderd.",
    "No API key configured. Open Settings.": "Geen API-sleutel ingesteld. Open de instellingen.",
    "No DMG download URL found": "Geen DMG-download-URL gevonden",
    "No IP address configured. Open Settings.": "Geen IP-adres ingesteld. Open de instellingen.",
    "No app bundle found in the DMG": "Geen app gevonden in de DMG",
    "No cameras discovered yet. Run Test Connection on the Connection tab.": "Nog geen camera's gevonden. Voer ‘Verbinding testen’ uit op het tabblad Verbinding.",
    "No cameras yet": "Nog geen camera's",
    "Not Now": "Niet nu",
    "Not configured": "Niet ingesteld",
    "Not verified": "Niet geverifieerd",
    "Offline": "Offline",
    "Open Settings": "Open instellingen",
    "Open in Protect": "Open in Protect",
    "PTZ (optional)": "PTZ (optioneel)",
    "PTZ · ARROW KEYS": "PTZ · PIJLTOETSEN",
    "PTZ control (optional)": "PTZ-bediening (optioneel)",
    "PTZ control uses the classic Protect API, which requires a local account. The Integration API (API Key) only exposes preset and patrol endpoints, not free-form movement.": "PTZ-bediening gebruikt de klassieke Protect-API, waarvoor een lokaal account nodig is. De integratie-API (API-sleutel) biedt alleen endpoints voor presets en patrouilles, geen vrije beweging.",
    "Pan & tilt (PTZ)": "Pannen en kantelen (PTZ)",
    "Pan / tilt": "Pannen / kantelen",
    "Pan left": "Naar links pannen",
    "Pan right": "Naar rechts pannen",
    "Password": "Wachtwoord",
    "Press shortcut…": "Druk op de sneltoets…",
    "QuickProtect can start automatically when you log in so your cameras are always one click away.": "QuickProtect kan automatisch starten wanneer je inlogt, zodat je camera's altijd één klik verwijderd zijn.",
    "QuickProtect – Settings": "QuickProtect – Instellingen",
    "Quit QuickProtect": "Stop QuickProtect",
    "RTSP · no media": "RTSP · geen media",
    "Reconnect": "Opnieuw verbinden",
    "Refresh": "Vernieuw",
    "Refresh cameras": "Camera's vernieuwen",
    "Reset size to Auto": "Formaat terugzetten op Auto",
    "Retry": "Opnieuw",
    "Search cameras": "Zoek camera's",
    "Settings": "Instellingen",
    "Settings…": "Instellingen…",
    "Shortcuts": "Sneltoetsen",
    "Show or hide the camera grid from anywhere.": "Toon of verberg het cameraraster vanaf elke plek.",
    "Show overlay controls": "Toon overlay-bediening",
    "Signed in · PTZ control ready": "Ingelogd · PTZ-bediening gereed",
    "Signed in — PTZ control ready": "Ingelogd — PTZ-bediening gereed",
    "Size": "Formaat",
    "Skip": "Sla over",
    "Small": "Klein",
    "Source": "Broncode",
    "Start QuickProtect at Login?": "QuickProtect starten bij inloggen?",
    "Startup": "Opstarten",
    "Step 1 of 3": "Stap 1 van 3",
    "Step 2 of 3": "Stap 2 van 3",
    "Step 3 of 3": "Stap 3 van 3",
    "Stream protocol": "Streamprotocol",
    "Stream unavailable": "Stream niet beschikbaar",
    "Test Connection": "Verbinding testen",
    "Theme": "Thema",
    "Tilt down": "Omlaag kantelen",
    "Tilt up": "Omhoog kantelen",
    "To pan and tilt PTZ cameras, QuickProtect needs a local admin account. The Integration API key only exposes preset and patrol endpoints, not free-form movement. You can skip this and add it later in Settings.": "Om PTZ-camera's te pannen en te kantelen heeft QuickProtect een lokaal beheerdersaccount nodig. De integratie-API-sleutel biedt alleen endpoints voor presets en patrouilles, geen vrije beweging. Je kunt dit overslaan en het later in de instellingen toevoegen.",
    "Toggle QuickProtect": "QuickProtect tonen/verbergen",
    "Updates": "Updates",
    "Username": "Gebruikersnaam",
    "Version": "Versie",
    "View License": "Bekijk licentie",
    "View fullscreen": "Toon op volledig scherm",
    "View on GitHub": "Bekijk op GitHub",
    "View the project source and releases.": "Bekijk de broncode en releases van het project.",
    "Welcome to\nQuickProtect.": "Welkom bij\nQuickProtect.",
    "Within QuickProtect": "Binnen QuickProtect",
    "You're all set.": "Alles is klaar.",
    "Digital zoom": "Digitale zoom",
    "Zoom": "Zoom",
    "Zoom (PTZ)": "Zoom (PTZ)",
    "Zoom in (I)": "Inzoomen (I)",
    "Zoom out (O)": "Uitzoomen (O)",
    "back to popover": "terug naar pop-over",
    "exit fullscreen": "volledig scherm sluiten",
    "just now": "zojuist",
    "v%@ available": "v%@ beschikbaar",
    "© 2026 Christian Bartels · Released under the MIT License.": "© 2026 Christian Bartels · Uitgebracht onder de MIT-licentie.",
    "⌘+scroll": "⌘+scrollen",
}

# ---------------------------------------------------------------------------
# Italian (informal "tu")
# ---------------------------------------------------------------------------
it = {
    "The controller isn't receiving video from this camera. Restarting the camera in UniFi Protect usually fixes this.": "Il controller non riceve video da questa telecamera. Riavviare la telecamera in UniFi Protect di solito risolve il problema.",
    # Keep-alive settings (were added to the catalog by hand; now sourced here).
    "Keep streams alive": "Mantieni attivi gli stream",
    "Kept-alive streams stay connected but skip video decoding while the panel is closed, cutting CPU use to nearly nothing. The picture catches up instantly on reopen.": "Gli stream mantenuti attivi restano connessi ma saltano la decodifica video finché il pannello è chiuso, riducendo l'uso della CPU quasi a zero. L'immagine si aggiorna all'istante alla riapertura.",
    "Off": "Disattivato",
    "Pause decoding while closed": "Sospendi la decodifica a pannello chiuso",
    "Streams stay connected for this long after closing, so a quick reopen shows video instantly": "Gli stream restano connessi per questo tempo dopo la chiusura, così il video appare subito alla riapertura",
    "Couldn't register this shortcut — it may be in use by another app.": "Impossibile registrare questa scorciatoia: potrebbe essere già usata da un'altra app.",
    "Trusted key": "Chiave attendibile",
    "New key": "Nuova chiave",
    "The controller is presenting a new certificate. This is expected if you reinstalled or replaced the controller — but if you didn't, it may indicate someone intercepting the connection. Compare the new key with the certificate your controller shows before trusting it.": "Il controller presenta un nuovo certificato. È normale se lo hai reinstallato o sostituito; in caso contrario potrebbe indicare che qualcuno sta intercettando la connessione. Confronta la nuova chiave con il certificato mostrato dal tuo controller prima di fidarti.",
    "Save Current View as New Profile…": "Salva vista attuale come nuovo profilo…",
    "Save Current View as New Profile": "Salva vista attuale come nuovo profilo",
    "Add Camera": "Aggiungi telecamera",
    "Save": "Salva",
    "Rename Profile…": "Rinomina profilo…",
    "Rename Profile": "Rinomina profilo",
    "Rename": "Rinomina",
    "Delete Profile": "Elimina profilo",
    "Switch layout profile": "Cambia profilo di layout",
    "Profile name": "Nome del profilo",
    "Default": "Predefinito",
    "Visibility, size, and order apply to the “%@” profile. Switch profiles from the popover header.": "Visibilità, dimensione e ordine si applicano al profilo «%@». Cambia profilo dall'intestazione del popover.",
    "Certificate": "Certificato",
    "Certificate changed": "Certificato modificato",
    "PTZ unavailable — check the username and password in Settings.": "PTZ non disponibile — controlla nome utente e password nelle impostazioni.",
    "The controller is presenting a new certificate (key %@…). This is expected if you reinstalled or replaced the controller — but if you didn't, it may indicate someone intercepting the connection. Trust it only if you recognize the change.": "Il controller presenta un nuovo certificato (chiave %@…). È previsto se hai reinstallato o sostituito il controller, ma in caso contrario potrebbe indicare che qualcuno sta intercettando la connessione. Fidati solo se riconosci la modifica.",
    "The controller's certificate changed. Open Settings to review and trust it.": "Il certificato del controller è cambiato. Apri le impostazioni per esaminarlo e fidarti.",
    "Trust new certificate": "Fidati del nuovo certificato",
    "Get update": "Ottieni aggiornamento",
    "API Key": "Chiave API",
    "About": "Informazioni",
    "All set": "Pronto",
    "App replacement failed: %@": "Sostituzione dell'app non riuscita: %@",
    "Accent": "Accento",
    "Appearance": "Aspetto",
    "Auto": "Auto",
    "Automatically start QuickProtect when you log in.": "Avvia QuickProtect automaticamente all'accesso.",
    "Back": "Indietro",
    "Back to grid (Esc)": "Torna alla griglia (Esc)",
    "Cameras": "Telecamere",
    "Can't reach controller": "Controller non raggiungibile",
    "Cancel": "Annulla",
    "Change": "Modifica",
    "Check for Updates": "Verifica aggiornamenti",
    "Checking…": "Verifica in corso…",
    "Classic API credentials": "Credenziali API classica",
    "Clear": "Cancella",
    "Clear search": "Cancella ricerca",
    "Click": "Clic",
    "Click the aperture icon in your menu bar to open the camera grid, or press your global shortcut.": "Fai clic sull'icona del diaframma nella barra dei menu per aprire la griglia delle telecamere, oppure usa la tua scorciatoia globale.",
    "Connect": "Connetti",
    "Connect your controller": "Connetti il tuo controller",
    "Connected": "Connesso",
    "Connected, but no cameras came back. Adopt one in the Protect app, then refresh.": "Connesso, ma nessuna telecamera trovata. Adottane una nell'app Protect, poi aggiorna.",
    "Connecting…": "Connessione…",
    "Connection": "Connessione",
    "Continue": "Continua",
    "Controller": "Controller",
    "Dark": "Scuro",
    "Disconnected": "Disconnesso",
    "Dismiss": "Chiudi",
    "Display fullscreen": "Mostra a schermo intero",
    "Display the keyboard-shortcut hints and the on-screen PTZ pad when a camera is in focus.": "Mostra i suggerimenti delle scorciatoie da tastiera e il pad PTZ sullo schermo quando una telecamera è ingrandita.",
    "Double-click": "Doppio clic",
    "Download failed: %@": "Download non riuscito: %@",
    "Enable": "Attiva",
    "Enter your UniFi Protect controller's local IP and an API key from its settings.": "Inserisci l'IP locale del tuo controller UniFi Protect e una chiave API dalle sue impostazioni.",
    "Esc": "Esc",
    "Exit / back": "Esci / indietro",
    "F  ·  Space": "F  ·  Spazio",
    "Failed to mount the update DMG": "Impossibile montare il DMG di aggiornamento",
    "Failed to save download: %@": "Impossibile salvare il download: %@",
    "Fill frame": "Riempi il riquadro",
    "Finish": "Fine",
    "Fit to frame": "Adatta al riquadro",
    "Focus camera": "Ingrandisci la telecamera",
    "Focus view": "Vista ingrandita",
    "Fullscreen": "Schermo intero",
    "Fullscreen (F)": "Schermo intero (F)",
    "General": "Generale",
    "Global": "Globale",
    "Grid": "Griglia",
    "Hide this camera": "Nascondi questa telecamera",
    "IP Address": "Indirizzo IP",
    "Install Update": "Installa aggiornamento",
    "Installed": "Installata",
    "Installing update…": "Installazione aggiornamento…",
    "Integration API key from controller settings": "Chiave dell'API di integrazione dalle impostazioni del controller",
    "Invalid IP address or URL.": "Indirizzo IP o URL non valido.",
    "Large": "Grande",
    "Last try: %@": "Ultimo tentativo: %@",
    "Launch at login": "Avvia all'accesso",
    "Legal": "Note legali",
    "License": "Licenza",
    "Light": "Chiaro",
    "Live UniFi Protect feeds, one click from your menu bar.": "Feed UniFi Protect in diretta, a un clic dalla barra dei menu.",
    "Local IP of your UniFi Protect controller": "IP locale del tuo controller UniFi Protect",
    "Local admin account on the Protect controller.": "Account amministratore locale sul controller Protect.",
    "Login failed — check the username and password": "Accesso non riuscito — controlla nome utente e password",
    "Login failed — check username and password": "Accesso non riuscito — controlla nome utente e password",
    "Medium": "Medio",
    "Menu-bar status app for UniFi Protect. Live camera feeds, one click away.": "App per la barra dei menu per UniFi Protect. Feed delle telecamere in diretta, a portata di clic.",
    "No API key configured. Open Settings.": "Nessuna chiave API configurata. Apri le impostazioni.",
    "No DMG download URL found": "Nessun URL di download del DMG trovato",
    "No IP address configured. Open Settings.": "Nessun indirizzo IP configurato. Apri le impostazioni.",
    "No app bundle found in the DMG": "Nessuna app trovata nel DMG",
    "No cameras discovered yet. Run Test Connection on the Connection tab.": "Nessuna telecamera rilevata finora. Esegui «Prova connessione» nella scheda Connessione.",
    "No cameras yet": "Ancora nessuna telecamera",
    "Not Now": "Non ora",
    "Not configured": "Non configurato",
    "Not verified": "Non verificato",
    "Offline": "Offline",
    "Open Settings": "Apri impostazioni",
    "Open in Protect": "Apri in Protect",
    "PTZ (optional)": "PTZ (opzionale)",
    "PTZ · ARROW KEYS": "PTZ · TASTI FRECCIA",
    "PTZ control (optional)": "Controllo PTZ (opzionale)",
    "PTZ control uses the classic Protect API, which requires a local account. The Integration API (API Key) only exposes preset and patrol endpoints, not free-form movement.": "Il controllo PTZ usa l'API Protect classica, che richiede un account locale. L'API di integrazione (chiave API) espone solo endpoint per preset e pattugliamenti, non il movimento libero.",
    "Pan & tilt (PTZ)": "Brandeggio e inclinazione (PTZ)",
    "Pan / tilt": "Brandeggio / inclinazione",
    "Pan left": "Brandeggio a sinistra",
    "Pan right": "Brandeggio a destra",
    "Password": "Password",
    "Press shortcut…": "Premi la scorciatoia…",
    "QuickProtect can start automatically when you log in so your cameras are always one click away.": "QuickProtect può avviarsi automaticamente all'accesso così le tue telecamere sono sempre a un clic.",
    "QuickProtect – Settings": "QuickProtect – Impostazioni",
    "Quit QuickProtect": "Esci da QuickProtect",
    "RTSP · no media": "RTSP · nessun contenuto",
    "Reconnect": "Riconnetti",
    "Refresh": "Aggiorna",
    "Refresh cameras": "Aggiorna telecamere",
    "Reset size to Auto": "Reimposta dimensione su Auto",
    "Retry": "Riprova",
    "Search cameras": "Cerca telecamere",
    "Settings": "Impostazioni",
    "Settings…": "Impostazioni…",
    "Shortcuts": "Scorciatoie",
    "Show or hide the camera grid from anywhere.": "Mostra o nasconde la griglia delle telecamere da qualsiasi punto.",
    "Show overlay controls": "Mostra i controlli in sovrimpressione",
    "Signed in · PTZ control ready": "Accesso effettuato · controllo PTZ pronto",
    "Signed in — PTZ control ready": "Accesso effettuato — controllo PTZ pronto",
    "Size": "Dimensione",
    "Skip": "Salta",
    "Small": "Piccolo",
    "Source": "Codice sorgente",
    "Start QuickProtect at Login?": "Avviare QuickProtect all'accesso?",
    "Startup": "Avvio",
    "Step 1 of 3": "Passaggio 1 di 3",
    "Step 2 of 3": "Passaggio 2 di 3",
    "Step 3 of 3": "Passaggio 3 di 3",
    "Stream protocol": "Protocollo di streaming",
    "Stream unavailable": "Stream non disponibile",
    "Test Connection": "Prova connessione",
    "Theme": "Tema",
    "Tilt down": "Inclina verso il basso",
    "Tilt up": "Inclina verso l'alto",
    "To pan and tilt PTZ cameras, QuickProtect needs a local admin account. The Integration API key only exposes preset and patrol endpoints, not free-form movement. You can skip this and add it later in Settings.": "Per il brandeggio e l'inclinazione delle telecamere PTZ, QuickProtect ha bisogno di un account amministratore locale. La chiave dell'API di integrazione espone solo endpoint per preset e pattugliamenti, non il movimento libero. Puoi saltare questo passaggio e aggiungerlo più tardi nelle impostazioni.",
    "Toggle QuickProtect": "Mostra/nascondi QuickProtect",
    "Updates": "Aggiornamenti",
    "Username": "Nome utente",
    "Version": "Versione",
    "View License": "Visualizza licenza",
    "View fullscreen": "Visualizza a schermo intero",
    "View on GitHub": "Visualizza su GitHub",
    "View the project source and releases.": "Visualizza il codice sorgente del progetto e le release.",
    "Welcome to\nQuickProtect.": "Ti diamo il benvenuto in\nQuickProtect.",
    "Within QuickProtect": "In QuickProtect",
    "You're all set.": "Tutto pronto.",
    "Digital zoom": "Zoom digitale",
    "Zoom": "Zoom",
    "Zoom (PTZ)": "Zoom (PTZ)",
    "Zoom in (I)": "Zoom avanti (I)",
    "Zoom out (O)": "Zoom indietro (O)",
    "back to popover": "torna al popover",
    "exit fullscreen": "esci da schermo intero",
    "just now": "proprio ora",
    "v%@ available": "v%@ disponibile",
    "© 2026 Christian Bartels · Released under the MIT License.": "© 2026 Christian Bartels · Rilasciato sotto licenza MIT.",
    "⌘+scroll": "⌘+scorrimento",
}

# ---------------------------------------------------------------------------
# Brazilian Portuguese ("você")
# ---------------------------------------------------------------------------
pt_br = {
    "The controller isn't receiving video from this camera. Restarting the camera in UniFi Protect usually fixes this.": "O controlador não está recebendo vídeo desta câmera. Reiniciar a câmera no UniFi Protect geralmente resolve isso.",
    # Keep-alive settings (were added to the catalog by hand; now sourced here).
    "Keep streams alive": "Manter streams ativos",
    "Kept-alive streams stay connected but skip video decoding while the panel is closed, cutting CPU use to nearly nothing. The picture catches up instantly on reopen.": "Os streams mantidos ativos permanecem conectados, mas pulam a decodificação de vídeo enquanto o painel está fechado, reduzindo o uso de CPU a quase nada. A imagem atualiza na hora ao reabrir.",
    "Off": "Desativado",
    "Pause decoding while closed": "Pausar a decodificação enquanto fechado",
    "Streams stay connected for this long after closing, so a quick reopen shows video instantly": "Os streams permanecem conectados por esse tempo após fechar, para o vídeo aparecer na hora ao reabrir",
    "Couldn't register this shortcut — it may be in use by another app.": "Não foi possível registrar este atalho — talvez outro app já o esteja usando.",
    "Trusted key": "Chave confiável",
    "New key": "Nova chave",
    "The controller is presenting a new certificate. This is expected if you reinstalled or replaced the controller — but if you didn't, it may indicate someone intercepting the connection. Compare the new key with the certificate your controller shows before trusting it.": "O controlador está apresentando um novo certificado. Isso é esperado se você o reinstalou ou substituiu — caso contrário, pode indicar que alguém está interceptando a conexão. Compare a nova chave com o certificado exibido pelo seu controlador antes de confiar nela.",
    "Save Current View as New Profile…": "Salvar visualização atual como novo perfil…",
    "Save Current View as New Profile": "Salvar visualização atual como novo perfil",
    "Add Camera": "Adicionar câmera",
    "Save": "Salvar",
    "Rename Profile…": "Renomear perfil…",
    "Rename Profile": "Renomear perfil",
    "Rename": "Renomear",
    "Delete Profile": "Excluir perfil",
    "Switch layout profile": "Alternar perfil de layout",
    "Profile name": "Nome do perfil",
    "Default": "Padrão",
    "Visibility, size, and order apply to the “%@” profile. Switch profiles from the popover header.": "Visibilidade, tamanho e ordem se aplicam ao perfil “%@”. Alterne entre perfis pelo cabeçalho do popover.",
    "Certificate": "Certificado",
    "Certificate changed": "Certificado alterado",
    "PTZ unavailable — check the username and password in Settings.": "PTZ indisponível — verifique o usuário e a senha nos ajustes.",
    "The controller is presenting a new certificate (key %@…). This is expected if you reinstalled or replaced the controller — but if you didn't, it may indicate someone intercepting the connection. Trust it only if you recognize the change.": "O controlador está apresentando um novo certificado (chave %@…). Isso é esperado se você reinstalou ou substituiu o controlador — caso contrário, pode indicar que alguém está interceptando a conexão. Confie nele somente se reconhecer a alteração.",
    "The controller's certificate changed. Open Settings to review and trust it.": "O certificado do controlador foi alterado. Abra os ajustes para revisá-lo e confiar nele.",
    "Trust new certificate": "Confiar no novo certificado",
    "Get update": "Obter atualização",
    "API Key": "Chave de API",
    "About": "Sobre",
    "All set": "Tudo pronto",
    "App replacement failed: %@": "Falha ao substituir o app: %@",
    "Accent": "Destaque",
    "Appearance": "Aparência",
    "Auto": "Auto",
    "Automatically start QuickProtect when you log in.": "Iniciar o QuickProtect automaticamente ao fazer login.",
    "Back": "Voltar",
    "Back to grid (Esc)": "Voltar à grade (Esc)",
    "Cameras": "Câmeras",
    "Can't reach controller": "Não foi possível conectar ao controlador",
    "Cancel": "Cancelar",
    "Change": "Alterar",
    "Check for Updates": "Buscar atualizações",
    "Checking…": "Verificando…",
    "Classic API credentials": "Credenciais da API clássica",
    "Clear": "Limpar",
    "Clear search": "Limpar busca",
    "Click": "Clique",
    "Click the aperture icon in your menu bar to open the camera grid, or press your global shortcut.": "Clique no ícone de abertura na barra de menus para abrir a grade de câmeras, ou use seu atalho global.",
    "Connect": "Conectar",
    "Connect your controller": "Conecte seu controlador",
    "Connected": "Conectado",
    "Connected, but no cameras came back. Adopt one in the Protect app, then refresh.": "Conectado, mas nenhuma câmera foi encontrada. Adote uma no app Protect e depois atualize.",
    "Connecting…": "Conectando…",
    "Connection": "Conexão",
    "Continue": "Continuar",
    "Controller": "Controlador",
    "Dark": "Escuro",
    "Disconnected": "Desconectado",
    "Dismiss": "Fechar",
    "Display fullscreen": "Exibir em tela cheia",
    "Display the keyboard-shortcut hints and the on-screen PTZ pad when a camera is in focus.": "Mostrar as dicas de atalhos de teclado e o painel PTZ na tela quando uma câmera está ampliada.",
    "Double-click": "Clique duplo",
    "Download failed: %@": "Falha no download: %@",
    "Enable": "Ativar",
    "Enter your UniFi Protect controller's local IP and an API key from its settings.": "Insira o IP local do seu controlador UniFi Protect e uma chave de API nas configurações dele.",
    "Esc": "Esc",
    "Exit / back": "Sair / voltar",
    "F  ·  Space": "F  ·  Espaço",
    "Failed to mount the update DMG": "Não foi possível montar o DMG de atualização",
    "Failed to save download: %@": "Não foi possível salvar o download: %@",
    "Fill frame": "Preencher o quadro",
    "Finish": "Concluir",
    "Fit to frame": "Ajustar ao quadro",
    "Focus camera": "Ampliar câmera",
    "Focus view": "Visualização ampliada",
    "Fullscreen": "Tela cheia",
    "Fullscreen (F)": "Tela cheia (F)",
    "General": "Geral",
    "Global": "Global",
    "Grid": "Grade",
    "Hide this camera": "Ocultar esta câmera",
    "IP Address": "Endereço IP",
    "Install Update": "Instalar atualização",
    "Installed": "Instalada",
    "Installing update…": "Instalando atualização…",
    "Integration API key from controller settings": "Chave da API de integração nas configurações do controlador",
    "Invalid IP address or URL.": "Endereço IP ou URL inválido.",
    "Large": "Grande",
    "Last try: %@": "Última tentativa: %@",
    "Launch at login": "Abrir ao fazer login",
    "Legal": "Jurídico",
    "License": "Licença",
    "Light": "Claro",
    "Live UniFi Protect feeds, one click from your menu bar.": "Transmissões UniFi Protect ao vivo, a um clique da sua barra de menus.",
    "Local IP of your UniFi Protect controller": "IP local do seu controlador UniFi Protect",
    "Local admin account on the Protect controller.": "Conta de administrador local no controlador Protect.",
    "Login failed — check the username and password": "Falha no login — verifique o usuário e a senha",
    "Login failed — check username and password": "Falha no login — verifique o usuário e a senha",
    "Medium": "Médio",
    "Menu-bar status app for UniFi Protect. Live camera feeds, one click away.": "App de barra de menus para UniFi Protect. Transmissões de câmeras ao vivo, a um clique de distância.",
    "No API key configured. Open Settings.": "Nenhuma chave de API configurada. Abra os ajustes.",
    "No DMG download URL found": "Nenhuma URL de download do DMG encontrada",
    "No IP address configured. Open Settings.": "Nenhum endereço IP configurado. Abra os ajustes.",
    "No app bundle found in the DMG": "Nenhum app encontrado no DMG",
    "No cameras discovered yet. Run Test Connection on the Connection tab.": "Nenhuma câmera detectada ainda. Execute “Testar conexão” na aba Conexão.",
    "No cameras yet": "Ainda não há câmeras",
    "Not Now": "Agora não",
    "Not configured": "Não configurado",
    "Not verified": "Não verificado",
    "Offline": "Offline",
    "Open Settings": "Abrir ajustes",
    "Open in Protect": "Abrir no Protect",
    "PTZ (optional)": "PTZ (opcional)",
    "PTZ · ARROW KEYS": "PTZ · TECLAS DE SETA",
    "PTZ control (optional)": "Controle PTZ (opcional)",
    "PTZ control uses the classic Protect API, which requires a local account. The Integration API (API Key) only exposes preset and patrol endpoints, not free-form movement.": "O controle PTZ usa a API clássica do Protect, que exige uma conta local. A API de integração (chave de API) só expõe endpoints de predefinições e patrulhas, não o movimento livre.",
    "Pan & tilt (PTZ)": "Girar e inclinar (PTZ)",
    "Pan / tilt": "Girar / inclinar",
    "Pan left": "Girar à esquerda",
    "Pan right": "Girar à direita",
    "Password": "Senha",
    "Press shortcut…": "Pressione o atalho…",
    "QuickProtect can start automatically when you log in so your cameras are always one click away.": "O QuickProtect pode iniciar automaticamente ao fazer login para que suas câmeras estejam sempre a um clique.",
    "QuickProtect – Settings": "QuickProtect – Ajustes",
    "Quit QuickProtect": "Encerrar o QuickProtect",
    "RTSP · no media": "RTSP · sem mídia",
    "Reconnect": "Reconectar",
    "Refresh": "Atualizar",
    "Refresh cameras": "Atualizar câmeras",
    "Reset size to Auto": "Redefinir tamanho para Auto",
    "Retry": "Tentar novamente",
    "Search cameras": "Buscar câmeras",
    "Settings": "Ajustes",
    "Settings…": "Ajustes…",
    "Shortcuts": "Atalhos",
    "Show or hide the camera grid from anywhere.": "Mostre ou oculte a grade de câmeras de qualquer lugar.",
    "Show overlay controls": "Mostrar controles sobrepostos",
    "Signed in · PTZ control ready": "Conectado · controle PTZ pronto",
    "Signed in — PTZ control ready": "Conectado — controle PTZ pronto",
    "Size": "Tamanho",
    "Skip": "Pular",
    "Small": "Pequeno",
    "Source": "Código-fonte",
    "Start QuickProtect at Login?": "Iniciar o QuickProtect ao fazer login?",
    "Startup": "Inicialização",
    "Step 1 of 3": "Etapa 1 de 3",
    "Step 2 of 3": "Etapa 2 de 3",
    "Step 3 of 3": "Etapa 3 de 3",
    "Stream protocol": "Protocolo de transmissão",
    "Stream unavailable": "Transmissão indisponível",
    "Test Connection": "Testar conexão",
    "Theme": "Tema",
    "Tilt down": "Inclinar para baixo",
    "Tilt up": "Inclinar para cima",
    "To pan and tilt PTZ cameras, QuickProtect needs a local admin account. The Integration API key only exposes preset and patrol endpoints, not free-form movement. You can skip this and add it later in Settings.": "Para girar e inclinar câmeras PTZ, o QuickProtect precisa de uma conta de administrador local. A chave da API de integração só expõe endpoints de predefinições e patrulhas, não o movimento livre. Você pode pular isto e adicionar depois nos ajustes.",
    "Toggle QuickProtect": "Mostrar/ocultar QuickProtect",
    "Updates": "Atualizações",
    "Username": "Usuário",
    "Version": "Versão",
    "View License": "Ver licença",
    "View fullscreen": "Ver em tela cheia",
    "View on GitHub": "Ver no GitHub",
    "View the project source and releases.": "Ver o código-fonte do projeto e as versões.",
    "Welcome to\nQuickProtect.": "Boas-vindas ao\nQuickProtect.",
    "Within QuickProtect": "Dentro do QuickProtect",
    "You're all set.": "Tudo pronto.",
    "Digital zoom": "Zoom digital",
    "Zoom": "Zoom",
    "Zoom (PTZ)": "Zoom (PTZ)",
    "Zoom in (I)": "Aproximar (I)",
    "Zoom out (O)": "Afastar (O)",
    "back to popover": "voltar à janela",
    "exit fullscreen": "sair da tela cheia",
    "just now": "agora mesmo",
    "v%@ available": "v%@ disponível",
    "© 2026 Christian Bartels · Released under the MIT License.": "© 2026 Christian Bartels · Lançado sob a licença MIT.",
    "⌘+scroll": "⌘+rolagem",
}

# ---------------------------------------------------------------------------
# Snapshot capture (S), added 2026-06-14. Register per standard: de=du, es=tú,
# nl=je, it=tu, pt-BR=você, fr=vous. "focused / in focus" uses the catalog's
# enlarge terminology (Großansicht / vue agrandie / vista ampliada / vergroot /
# ingrandita / ampliada) — never optical-focus wording. Columns: de, fr, es,
# nl, it, pt-BR.
# ---------------------------------------------------------------------------
_snapshot = {
    "Snapshot":    ("Schnappschuss", "Instantané", "Instantánea", "Momentopname", "Istantanea", "Instantâneo"),
    "snapshot":    ("Schnappschuss", "instantané", "instantánea", "momentopname", "istantanea", "instantâneo"),
    "Snapshots":   ("Schnappschüsse", "Instantanés", "Instantáneas", "Momentopnamen", "Istantanee", "Instantâneos"),
    "Destination": ("Ziel", "Destination", "Destino", "Bestemming", "Destinazione", "Destino"),
    "Clipboard":   ("Zwischenablage", "Presse-papiers", "Portapapeles", "Klembord", "Appunti", "Área de transferência"),
    "Folder":      ("Ordner", "Dossier", "Carpeta", "Map", "Cartella", "Pasta"),
    "Save folder": ("Speicherordner", "Dossier d'enregistrement", "Carpeta de guardado", "Opslagmap", "Cartella di salvataggio", "Pasta de salvamento"),
    "Choose":      ("Auswählen", "Choisir", "Elegir", "Kiezen", "Scegli", "Escolher"),
    "Choose…":     ("Auswählen…", "Choisir…", "Elegir…", "Kiezen…", "Scegli…", "Escolher…"),
    "Choose a folder for saved snapshots": ("Wähle einen Ordner für gespeicherte Schnappschüsse", "Choisissez un dossier pour les instantanés enregistrés", "Elige una carpeta para las instantáneas guardadas", "Kies een map voor opgeslagen momentopnamen", "Scegli una cartella per le istantanee salvate", "Escolha uma pasta para os instantâneos salvos"),
    "Choose a snapshot folder in Settings": ("Wähle in den Einstellungen einen Schnappschuss-Ordner", "Choisissez un dossier d'instantanés dans les Réglages", "Elige una carpeta de instantáneas en Ajustes", "Kies een momentopnamemap in Instellingen", "Scegli una cartella per le istantanee nelle Impostazioni", "Escolha uma pasta de instantâneos em Ajustes"),
    "Snapshots are saved here as PNG files.": ("Schnappschüsse werden hier als PNG-Dateien gespeichert.", "Les instantanés sont enregistrés ici sous forme de fichiers PNG.", "Las instantáneas se guardan aquí como archivos PNG.", "Momentopnamen worden hier opgeslagen als PNG-bestanden.", "Le istantanee vengono salvate qui come file PNG.", "Os instantâneos são salvos aqui como arquivos PNG."),
    "Press S on a focused camera to capture a snapshot.": ("Drücke S in der Großansicht, um einen Schnappschuss aufzunehmen.", "Appuyez sur S sur une caméra en vue agrandie pour capturer un instantané.", "Pulsa S en una cámara en vista ampliada para capturar una instantánea.", "Druk op S wanneer een camera vergroot is om een momentopname te maken.", "Premi S quando una telecamera è ingrandita per acquisire un'istantanea.", "Pressione S quando uma câmera estiver ampliada para capturar um instantâneo."),
    "Capturing…":  ("Aufnahme läuft…", "Capture en cours…", "Capturando…", "Bezig met vastleggen…", "Acquisizione…", "Capturando…"),
    "Copied to clipboard": ("In die Zwischenablage kopiert", "Copié dans le presse-papiers", "Copiado al portapapeles", "Gekopieerd naar klembord", "Copiato negli appunti", "Copiado para a área de transferência"),
    "Snapshot saved": ("Schnappschuss gespeichert", "Instantané enregistré", "Instantánea guardada", "Momentopname opgeslagen", "Istantanea salvata", "Instantâneo salvo"),
    "Snapshot failed": ("Schnappschuss fehlgeschlagen", "Échec de l'instantané", "Error en la instantánea", "Momentopname mislukt", "Istantanea non riuscita", "Falha no instantâneo"),
}
for _k, (_de, _fr, _es, _nl, _it, _pt) in _snapshot.items():
    de[_k] = _de; fr[_k] = _fr; es[_k] = _es; nl[_k] = _nl; it[_k] = _it; pt_br[_k] = _pt

# ---------------------------------------------------------------------------
# PiP / audio / HUD strings that predate the snapshot feature but were never
# registered. Same standard: de=du, fr=vous, es=tú, nl=je, it=tu, pt-BR=você;
# straight apostrophes (U+0027). Notes:
#   • "Picture-in-picture when focused": "focused" is the enlarge feature, so it
#     reuses the catalog's enlarge terminology (Großansicht / vue agrandie /
#     vista ampliada / vergrote weergave / vista ingrandita / visualização
#     ampliada), never optical-focus wording. PiP itself uses each locale's
#     Apple platform term.
#   • "LIVE" is left untranslated in every locale — it's a universal status
#     indicator (same convention as on-air badges everywhere); translating it
#     would only reduce recognizability.
#   • "pan / tilt" and "zoom" are the lowercase HUD variants. The catalog
#     already has the capitalized "Pan / tilt" and "Zoom" used by the focus
#     hints; these add the lowercase forms so the HUD keeps its own casing.
#     German nouns are normally capitalized, but the HUD's deliberate lowercase
#     styling is preserved here on purpose. Columns: de, fr, es, nl, it, pt-BR.
# ---------------------------------------------------------------------------
_pip_audio = {
    "Swap with main view (C)": ("Mit der Hauptansicht tauschen (C)", "Permuter avec la vue principale (C)", "Intercambiar con la vista principal (C)", "Wisselen met de hoofdweergave (C)", "Scambia con la vista principale (C)", "Trocar com a visualização principal (C)"),
    "Picture-in-picture when focused": ("Bild-in-Bild in der Großansicht", "Image dans l'image en vue agrandie", "Imagen en imagen en la vista ampliada", "Beeld-in-beeld bij vergrote weergave", "Immagine nell'immagine nella vista ingrandita", "Imagem sobre imagem na visualização ampliada"),
    "Also show on the grid tile": ("Auch auf der Rasterkachel anzeigen", "Afficher aussi sur la tuile de la grille", "Mostrar también en el mosaico de la cuadrícula", "Ook op de rastertegel tonen", "Mostra anche sul riquadro della griglia", "Mostrar também no bloco da grade"),
    "Unmute (M)": ("Stummschaltung aufheben (M)", "Réactiver le son (M)", "Activar sonido (M)", "Dempen opheffen (M)", "Attiva audio (M)", "Ativar som (M)"),
    "Mute (M)": ("Stummschalten (M)", "Couper le son (M)", "Silenciar (M)", "Dempen (M)", "Disattiva audio (M)", "Desativar som (M)"),
    "Mute": ("Stummschalten", "Couper le son", "Silenciar", "Dempen", "Disattiva audio", "Desativar som"),
    "LIVE": ("LIVE", "LIVE", "LIVE", "LIVE", "LIVE", "LIVE"),
    "pan / tilt": ("schwenken / neigen", "panoramique / inclinaison", "giro / inclinación", "pannen / kantelen", "brandeggio / inclinazione", "girar / inclinar"),
    "zoom": ("zoom", "zoom", "zoom", "zoom", "zoom", "zoom"),
}
for _k, (_de, _fr, _es, _nl, _it, _pt) in _pip_audio.items():
    de[_k] = _de; fr[_k] = _fr; es[_k] = _es; nl[_k] = _nl; it[_k] = _it; pt_br[_k] = _pt

# ---------------------------------------------------------------------------
# Stream quality selection. "Auto" and "Medium" already exist (reused). The
# High/Low quality words take the feminine forms that agree with "quality"
# (qualité/calidad/qualità/qualidade) in the romance locales. The hint uses the
# catalog's enlarge terminology (Großansicht / vue agrandie / …), never optical
# focus, and German keeps full du-imperatives. Columns: de, fr, es, nl, it, pt-BR.
# ---------------------------------------------------------------------------
_streaming = {
    "High": ("Hoch", "Haute", "Alta", "Hoog", "Alta", "Alta"),
    "Low": ("Niedrig", "Basse", "Baja", "Laag", "Bassa", "Baixa"),
    "Streaming": ("Streaming", "Diffusion", "Transmisión", "Streamen", "Streaming", "Transmissão"),
    "Stream quality": ("Streamqualität", "Qualité du flux", "Calidad del flujo", "Streamkwaliteit", "Qualità dello stream", "Qualidade da transmissão"),
    "Use default": ("Standard verwenden", "Utiliser la valeur par défaut", "Usar predeterminada", "Standaard gebruiken", "Usa predefinita", "Usar padrão"),
    "Default stream quality": ("Standard-Streamqualität", "Qualité du flux par défaut", "Calidad de flujo predeterminada", "Standaard streamkwaliteit", "Qualità stream predefinita", "Qualidade de transmissão padrão"),
    "Auto streams low quality in the grid and high quality when a camera is enlarged — saving CPU and bandwidth. Override per camera by right-clicking its tile.": (
        "Auto streamt im Raster in niedriger Qualität und in der Großansicht in hoher Qualität – das spart CPU und Bandbreite. Überschreibe die Einstellung pro Kamera per Rechtsklick auf die Kachel.",
        "Auto diffuse en basse qualité dans la grille et en haute qualité lorsqu'une caméra est agrandie, ce qui économise le processeur et la bande passante. Remplacez ce réglage par caméra d'un clic droit sur sa tuile.",
        "Auto transmite en baja calidad en la cuadrícula y en alta calidad cuando se amplía una cámara, lo que ahorra CPU y ancho de banda. Anula este ajuste por cámara haciendo clic derecho en su mosaico.",
        "Auto streamt in lage kwaliteit in het raster en in hoge kwaliteit wanneer een camera vergroot is — dat bespaart CPU en bandbreedte. Overschrijf dit per camera door rechts te klikken op de tegel.",
        "Auto trasmette in bassa qualità nella griglia e in alta qualità quando una telecamera è ingrandita, risparmiando CPU e larghezza di banda. Sostituisci l'impostazione per telecamera facendo clic con il tasto destro sul riquadro.",
        "Auto transmite em baixa qualidade na grade e em alta qualidade quando uma câmera é ampliada — economizando CPU e largura de banda. Substitua por câmera clicando com o botão direito no bloco."),
}
for _k, (_de, _fr, _es, _nl, _it, _pt) in _streaming.items():
    de[_k] = _de; fr[_k] = _fr; es[_k] = _es; nl[_k] = _nl; it[_k] = _it; pt_br[_k] = _pt

# ---------------------------------------------------------------------------
# Pinned floating windows (picture-in-picture). Menu items use neutral
# imperatives; German keeps the informal-du register. "Save snapshot" is the
# pinned window's hover button (the toast strings are reused from the focus
# view). Columns: de, fr, es, nl, it, pt-BR.
# ---------------------------------------------------------------------------
_pinned = {
    "Pin as Floating Window": ("Als schwebendes Fenster anheften", "Épingler comme fenêtre flottante", "Fijar como ventana flotante", "Vastmaken als zwevend venster", "Blocca come finestra mobile", "Fixar como janela flutuante"),
    "Unpin Floating Window": ("Schwebendes Fenster lösen", "Détacher la fenêtre flottante", "Desfijar ventana flotante", "Zwevend venster losmaken", "Sblocca finestra mobile", "Desafixar janela flutuante"),
    "Save snapshot": ("Schnappschuss sichern", "Enregistrer la capture", "Guardar instantánea", "Momentopname bewaren", "Salva istantanea", "Salvar instantâneo"),
    "Drag to resize": ("Zum Anpassen ziehen", "Glisser pour redimensionner", "Arrastra para cambiar el tamaño", "Sleep om te vergroten/verkleinen", "Trascina per ridimensionare", "Arraste para redimensionar"),
}
for _k, (_de, _fr, _es, _nl, _it, _pt) in _pinned.items():
    de[_k] = _de; fr[_k] = _fr; es[_k] = _es; nl[_k] = _nl; it[_k] = _it; pt_br[_k] = _pt

# ---------------------------------------------------------------------------
# App Store promotion (non-App-Store builds only: launch nudge, update prompt,
# Settings → Updates section) and the doorbell's secondary lens. "Mac App
# Store" and "GitHub" are proper nouns and stay as they are. German keeps the
# informal du ("Hol dir …"), French stays formal. Columns: de, fr, es, nl, it, pt-BR.
# ---------------------------------------------------------------------------
_appstore = {
    "Automatic updates — always on the latest version, no manual downloads.": (
        "Automatische Updates – immer auf der neuesten Version, ohne manuelle Downloads.",
        "Mises à jour automatiques — toujours la dernière version, sans téléchargement manuel.",
        "Actualizaciones automáticas: siempre la última versión, sin descargas manuales.",
        "Automatische updates – altijd de nieuwste versie, zonder handmatige downloads.",
        "Aggiornamenti automatici: sempre l'ultima versione, senza download manuali.",
        "Atualizações automáticas — sempre na versão mais recente, sem downloads manuais."),
    "Signed and notarized by Apple — installs cleanly, with no security warnings.": (
        "Von Apple signiert und beglaubigt – installiert sich sauber, ohne Sicherheitswarnungen.",
        "Signée et notarisée par Apple — s'installe proprement, sans avertissement de sécurité.",
        "Firmada y notarizada por Apple: se instala sin problemas ni avisos de seguridad.",
        "Ondertekend en genotariseerd door Apple – installeert netjes, zonder beveiligingswaarschuwingen.",
        "Firmata e autenticata da Apple: si installa senza problemi né avvisi di sicurezza.",
        "Assinado e autenticado pela Apple — instala sem problemas nem avisos de segurança."),
    "Sandboxed for extra security.": (
        "Läuft in der Sandbox – für zusätzliche Sicherheit.",
        "Exécutée en bac à sable pour plus de sécurité.",
        "Aislada en un sandbox para mayor seguridad.",
        "Draait in een sandbox voor extra beveiliging.",
        "Eseguita in sandbox per maggiore sicurezza.",
        "Executado em sandbox para mais segurança."),
    "Supports development and helps keep QuickProtect improving.": (
        "Unterstützt die Entwicklung und hilft, QuickProtect weiter zu verbessern.",
        "Soutient le développement et aide QuickProtect à s'améliorer.",
        "Apoya el desarrollo y ayuda a que QuickProtect siga mejorando.",
        "Ondersteunt de ontwikkeling en helpt QuickProtect beter te maken.",
        "Sostiene lo sviluppo e aiuta QuickProtect a migliorare.",
        "Apoia o desenvolvimento e ajuda o QuickProtect a continuar melhorando."),
    "View on the App Store": ("Im App Store ansehen", "Voir sur l'App Store", "Ver en el App Store", "Bekijk in de App Store", "Vedi sull'App Store", "Ver na App Store"),
    "Download from GitHub": ("Von GitHub laden", "Télécharger depuis GitHub", "Descargar de GitHub", "Downloaden van GitHub", "Scarica da GitHub", "Baixar do GitHub"),
    "Not now": ("Jetzt nicht", "Pas maintenant", "Ahora no", "Niet nu", "Non ora", "Agora não"),
    "Later": ("Später", "Plus tard", "Más tarde", "Later", "Più tardi", "Mais tarde"),
    "QuickProtect is on the App Store": ("QuickProtect gibt es im App Store", "QuickProtect est sur l'App Store", "QuickProtect está en el App Store", "QuickProtect staat in de App Store", "QuickProtect è sull'App Store", "O QuickProtect está na App Store"),
    "A new version is available": ("Eine neue Version ist verfügbar", "Une nouvelle version est disponible", "Hay una nueva versión disponible", "Er is een nieuwe versie beschikbaar", "È disponibile una nuova versione", "Uma nova versão está disponível"),
    "QuickProtect %@ is out. The easiest way to stay up to date — and get a signed, hassle-free install — is the Mac App Store.": (
        "QuickProtect %@ ist da. Am einfachsten bleibst du aktuell – mit einer signierten, unkomplizierten Installation – über den Mac App Store.",
        "QuickProtect %@ est disponible. Le moyen le plus simple de rester à jour — avec une installation signée et sans tracas — est le Mac App Store.",
        "QuickProtect %@ ya está disponible. La forma más fácil de estar al día, con una instalación firmada y sin complicaciones, es la Mac App Store.",
        "QuickProtect %@ is uit. De makkelijkste manier om up-to-date te blijven – met een ondertekende installatie zonder gedoe – is de Mac App Store.",
        "QuickProtect %@ è disponibile. Il modo più semplice per restare aggiornato, con un'installazione firmata e senza problemi, è il Mac App Store.",
        "O QuickProtect %@ foi lançado. A maneira mais fácil de se manter atualizado — com uma instalação assinada e sem complicações — é a Mac App Store."),
    "Prefer automatic updates and an Apple-signed, hassle-free install? Get QuickProtect from the Mac App Store.": (
        "Lieber automatische Updates und eine von Apple signierte, unkomplizierte Installation? Hol dir QuickProtect aus dem Mac App Store.",
        "Vous préférez les mises à jour automatiques et une installation signée par Apple, sans tracas ? Obtenez QuickProtect sur le Mac App Store.",
        "¿Prefieres actualizaciones automáticas y una instalación firmada por Apple sin complicaciones? Consigue QuickProtect en la Mac App Store.",
        "Liever automatische updates en een door Apple ondertekende installatie zonder gedoe? Haal QuickProtect uit de Mac App Store.",
        "Preferisci aggiornamenti automatici e un'installazione firmata da Apple, senza problemi? Scarica QuickProtect dal Mac App Store.",
        "Prefere atualizações automáticas e uma instalação assinada pela Apple, sem complicações? Baixe o QuickProtect na Mac App Store."),
    "Mac App Store": ("Mac App Store",) * 6,
    "GitHub": ("GitHub",) * 6,
    "Get the App Store edition": ("Hol dir die App-Store-Version", "Obtenir la version App Store", "Consigue la versión del App Store", "Haal de App Store-versie", "Ottieni la versione App Store", "Obtenha a versão da App Store"),
    "Automatic updates, an Apple-signed install with no security warnings, and it supports development.": (
        "Automatische Updates, eine von Apple signierte Installation ohne Sicherheitswarnungen – und du unterstützt die Entwicklung.",
        "Mises à jour automatiques, installation signée par Apple sans avertissement de sécurité, et un soutien au développement.",
        "Actualizaciones automáticas, una instalación firmada por Apple sin avisos de seguridad, y apoyas el desarrollo.",
        "Automatische updates, een door Apple ondertekende installatie zonder beveiligingswaarschuwingen, en je ondersteunt de ontwikkeling.",
        "Aggiornamenti automatici, un'installazione firmata da Apple senza avvisi di sicurezza, e sostieni lo sviluppo.",
        "Atualizações automáticas, uma instalação assinada pela Apple sem avisos de segurança, e você apoia o desenvolvimento."),
    "Package Camera": ("Paketkamera", "Caméra colis", "Cámara de paquetes", "Pakketcamera", "Fotocamera pacchi", "Câmera de encomendas"),
}
for _k, (_de, _fr, _es, _nl, _it, _pt) in _appstore.items():
    de[_k] = _de; fr[_k] = _fr; es[_k] = _es; nl[_k] = _nl; it[_k] = _it; pt_br[_k] = _pt

LANGS = {"de": de, "fr": fr, "es": es, "nl": nl, "it": it, "pt-BR": pt_br}

# ---------------------------------------------------------------------------
# Plurals — every key has (one, other) per language.
# ---------------------------------------------------------------------------
plurals = {
    "%lld streams": {
        "en": ("%lld stream", "%lld streams"),
        "de": ("%lld Stream", "%lld Streams"),
        "fr": ("%lld flux", "%lld flux"),
        "es": ("%lld transmisión", "%lld transmisiones"),
        "nl": ("%lld stream", "%lld streams"),
        "it": ("%lld stream", "%lld stream"),
        "pt-BR": ("%lld transmissão", "%lld transmissões"),
    },
    "%lld cameras detected.": {
        "en": ("%lld camera detected.", "%lld cameras detected."),
        "de": ("%lld Kamera erkannt.", "%lld Kameras erkannt."),
        "fr": ("%lld caméra détectée.", "%lld caméras détectées."),
        "es": ("%lld cámara detectada.", "%lld cámaras detectadas."),
        "nl": ("%lld camera gedetecteerd.", "%lld camera's gedetecteerd."),
        "it": ("%lld telecamera rilevata.", "%lld telecamere rilevate."),
        "pt-BR": ("%lld câmera detectada.", "%lld câmeras detectadas."),
    },
    "%lld seconds ago": {
        "en": ("%lld second ago", "%lld seconds ago"),
        "de": ("vor %lld Sekunde", "vor %lld Sekunden"),
        "fr": ("il y a %lld seconde", "il y a %lld secondes"),
        "es": ("hace %lld segundo", "hace %lld segundos"),
        "nl": ("%lld seconde geleden", "%lld seconden geleden"),
        "it": ("%lld secondo fa", "%lld secondi fa"),
        "pt-BR": ("há %lld segundo", "há %lld segundos"),
    },
    "%lld minutes ago": {
        "en": ("%lld minute ago", "%lld minutes ago"),
        "de": ("vor %lld Minute", "vor %lld Minuten"),
        "fr": ("il y a %lld minute", "il y a %lld minutes"),
        "es": ("hace %lld minuto", "hace %lld minutos"),
        "nl": ("%lld minuut geleden", "%lld minuten geleden"),
        "it": ("%lld minuto fa", "%lld minuti fa"),
        "pt-BR": ("há %lld minuto", "há %lld minutos"),
    },
    "Connected · %lld cameras found": {
        "en": ("Connected · %lld camera found", "Connected · %lld cameras found"),
        "de": ("Verbunden · %lld Kamera gefunden", "Verbunden · %lld Kameras gefunden"),
        "fr": ("Connecté · %lld caméra trouvée", "Connecté · %lld caméras trouvées"),
        "es": ("Conectado · %lld cámara encontrada", "Conectado · %lld cámaras encontradas"),
        "nl": ("Verbonden · %lld camera gevonden", "Verbonden · %lld camera's gevonden"),
        "it": ("Connesso · %lld telecamera trovata", "Connesso · %lld telecamere trovate"),
        "pt-BR": ("Conectado · %lld câmera encontrada", "Conectado · %lld câmeras encontradas"),
    },
    "Connected — %lld cameras found": {
        "en": ("Connected — %lld camera found", "Connected — %lld cameras found"),
        "de": ("Verbunden – %lld Kamera gefunden", "Verbunden – %lld Kameras gefunden"),
        "fr": ("Connecté — %lld caméra trouvée", "Connecté — %lld caméras trouvées"),
        "es": ("Conectado — %lld cámara encontrada", "Conectado — %lld cámaras encontradas"),
        "nl": ("Verbonden — %lld camera gevonden", "Verbonden — %lld camera's gevonden"),
        "it": ("Connesso — %lld telecamera trovata", "Connesso — %lld telecamere trovate"),
        "pt-BR": ("Conectado — %lld câmera encontrada", "Conectado — %lld câmeras encontradas"),
    },
}

# ---------------------------------------------------------------------------
# Parity check: every language must cover exactly the German key set.
# ---------------------------------------------------------------------------
ref = set(de)
problems = False
for code, d in LANGS.items():
    if code == "de":
        continue
    missing = ref - set(d)
    extra = set(d) - ref
    if missing or extra:
        problems = True
        print(f"[{code}] MISSING ({len(missing)}): {sorted(missing)}")
        print(f"[{code}] EXTRA ({len(extra)}): {sorted(extra)}")
if problems:
    print("Parity check FAILED — fix the dictionaries above.")
    sys.exit(1)
print("Parity check OK — all languages cover the full key set.")

# ---------------------------------------------------------------------------
# Build the catalog.
# ---------------------------------------------------------------------------
def unit(value):
    return {"stringUnit": {"state": "translated", "value": value}}

def plural_loc(one, other):
    return {"variations": {"plural": {"one": unit(one), "other": unit(other)}}}

strings = collections.OrderedDict()
for k in sorted(de):
    locs = {code: unit(d[k]) for code, d in LANGS.items()}
    strings[k] = {"extractionState": "manual", "localizations": locs}

for k in sorted(plurals):
    p = plurals[k]
    locs = {code: plural_loc(*vals) for code, vals in p.items()}
    strings[k] = {"extractionState": "manual", "localizations": locs}

catalog = {"sourceLanguage": "en", "strings": strings, "version": "1.0"}

_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out = os.path.join(_root, "QuickProtect", "Localizable.xcstrings")
with open(out, "w", encoding="utf-8") as f:
    json.dump(catalog, f, ensure_ascii=False, indent=2)
    f.write("\n")
print(f"Wrote {len(strings)} keys × {len(LANGS)} languages to {out}")
