#!/usr/bin/env python3
import json, collections, sys, os

# ---------------------------------------------------------------------------
# German (informal "du") — the existing, reviewed translation.
# ---------------------------------------------------------------------------
de = {
    "API Key": "API-Schlüssel",
    "About": "Über",
    "All set": "Fertig",
    "App replacement failed: %@": "App-Austausch fehlgeschlagen: %@",
    "Accent": "Akzentfarbe",
    "Appearance": "Darstellung",
    "Auto": "Auto",
    "Automatically start QuickProtect when you log in.": "QuickProtect automatisch starten, wenn du dich anmeldest.",
    "Back": "Zurück",
    "Back to grid (Esc)": "Zurück zum Raster (Esc)",
    "Cameras": "Kameras",
    "Can't reach controller": "Controller nicht erreichbar",
    "Cancel": "Abbrechen",
    "Change": "Ändern",
    "Check for Updates": "Nach Updates suchen",
    "Checking…": "Suche läuft…",
    "Classic API credentials": "Anmeldedaten für klassische API",
    "Clear": "Löschen",
    "Clear search": "Suche löschen",
    "Click": "Klick",
    "Click the aperture icon in your menu bar to open the camera grid, or press your global shortcut.": "Klick auf das Blendensymbol in der Menüleiste, um das Kameraraster zu öffnen, oder drück deinen globalen Kurzbefehl.",
    "Connect": "Verbinden",
    "Connect your controller": "Controller verbinden",
    "Connected": "Verbunden",
    "Connected, but no cameras came back. Adopt one in the Protect app, then refresh.": "Verbunden, aber keine Kameras gefunden. Übernimm eine in der Protect-App und aktualisiere dann.",
    "Connecting…": "Verbinden…",
    "Connection": "Verbindung",
    "Continue": "Weiter",
    "Controller": "Controller",
    "Dark": "Dunkel",
    "Disconnected": "Getrennt",
    "Dismiss": "Verwerfen",
    "Display fullscreen": "Vollbild anzeigen",
    "Display the keyboard-shortcut hints and the on-screen PTZ pad when a camera is in focus.": "Tastaturkurzbefehl-Hinweise und das PTZ-Steuerkreuz anzeigen, wenn eine Kamera im Fokus ist.",
    "Double-click": "Doppelklick",
    "Download failed: %@": "Download fehlgeschlagen: %@",
    "Enable": "Aktivieren",
    "Enter your UniFi Protect controller's local IP and an API key from its settings.": "Gib die lokale IP deines UniFi-Protect-Controllers und einen API-Schlüssel aus dessen Einstellungen ein.",
    "Esc": "Esc",
    "Exit / back": "Beenden / Zurück",
    "F  ·  Space": "F  ·  Leertaste",
    "Failed to mount the update DMG": "Update-DMG konnte nicht eingebunden werden",
    "Failed to save download: %@": "Download konnte nicht gespeichert werden: %@",
    "Fill frame": "Bild füllen",
    "Finish": "Fertig",
    "Fit to frame": "Einpassen",
    "Focus camera": "Kamera fokussieren",
    "Focus view": "Fokusansicht",
    "Fullscreen": "Vollbild",
    "Fullscreen (F)": "Vollbild (F)",
    "General": "Allgemein",
    "Global": "Global",
    "Grid": "Raster",
    "Hide this camera": "Diese Kamera ausblenden",
    "IP Address": "IP-Adresse",
    "Install Update": "Update installieren",
    "Installed": "Installiert",
    "Installing update…": "Update wird installiert…",
    "Integration API key from controller settings": "Integrations-API-Schlüssel aus den Controller-Einstellungen",
    "Invalid IP address or URL.": "Ungültige IP-Adresse oder URL.",
    "Large": "Groß",
    "Last try: %@": "Letzter Versuch: %@",
    "Launch at login": "Beim Anmelden starten",
    "Legal": "Rechtliches",
    "License": "Lizenz",
    "Light": "Hell",
    "Live UniFi Protect feeds, one click from your menu bar.": "Live-UniFi-Protect-Feeds, nur einen Klick von der Menüleiste entfernt.",
    "Local IP of your UniFi Protect controller": "Lokale IP des UniFi-Protect-Controllers",
    "Local admin account on the Protect controller.": "Lokales Admin-Konto auf dem Protect-Controller.",
    "Login failed — check the username and password": "Anmeldung fehlgeschlagen – prüf Benutzername und Passwort",
    "Login failed — check username and password": "Anmeldung fehlgeschlagen – prüf Benutzername und Passwort",
    "Medium": "Mittel",
    "Menu-bar status app for UniFi Protect. Live camera feeds, one click away.": "Menüleisten-App für UniFi Protect. Live-Kamerafeeds, nur einen Klick entfernt.",
    "No API key configured. Open Settings.": "Kein API-Schlüssel konfiguriert. Öffne die Einstellungen.",
    "No DMG download URL found": "Keine DMG-Download-URL gefunden",
    "No IP address configured. Open Settings.": "Keine IP-Adresse konfiguriert. Öffne die Einstellungen.",
    "No app bundle found in the DMG": "Kein App-Bundle in der DMG gefunden",
    "No cameras discovered yet. Run Test Connection on the Connection tab.": "Noch keine Kameras gefunden. Führe „Verbindung testen“ im Tab „Verbindung“ aus.",
    "No cameras yet": "Noch keine Kameras",
    "Not Now": "Jetzt nicht",
    "Not configured": "Nicht konfiguriert",
    "Not verified": "Nicht verifiziert",
    "Offline": "Offline",
    "Open Settings": "Einstellungen öffnen",
    "Open in Protect": "In Protect öffnen",
    "PTZ (optional)": "PTZ (optional)",
    "PTZ · ARROW KEYS": "PTZ · PFEILTASTEN",
    "PTZ control (optional)": "PTZ-Steuerung (optional)",
    "PTZ control uses the classic Protect API, which requires a local account. The Integration API (API Key) does not expose PTZ endpoints.": "Die PTZ-Steuerung nutzt die klassische Protect-API, die ein lokales Konto erfordert. Die Integrations-API (API-Schlüssel) bietet keine PTZ-Endpunkte.",
    "Pan & tilt (PTZ)": "Schwenken & Neigen (PTZ)",
    "Pan / tilt": "Schwenken / Neigen",
    "Pan left": "Nach links schwenken",
    "Pan right": "Nach rechts schwenken",
    "Password": "Passwort",
    "Press shortcut…": "Kurzbefehl drücken…",
    "QuickProtect can start automatically when you log in so your cameras are always one click away.": "QuickProtect kann beim Anmelden automatisch starten, damit deine Kameras immer nur einen Klick entfernt sind.",
    "QuickProtect – Settings": "QuickProtect – Einstellungen",
    "Quit QuickProtect": "QuickProtect beenden",
    "RTSP · no media": "RTSP · keine Medien",
    "Reconnect": "Erneut verbinden",
    "Refresh": "Aktualisieren",
    "Refresh cameras": "Kameras aktualisieren",
    "Reset size to Auto": "Größe auf Auto zurücksetzen",
    "Retry": "Wiederholen",
    "Search cameras": "Kameras suchen",
    "Settings": "Einstellungen",
    "Settings…": "Einstellungen…",
    "Shortcuts": "Kurzbefehle",
    "Show or hide the camera grid from anywhere.": "Das Kameraraster von überall ein- oder ausblenden.",
    "Show overlay controls": "Overlay-Steuerung anzeigen",
    "Signed in · PTZ control ready": "Angemeldet · PTZ-Steuerung bereit",
    "Signed in — PTZ control ready": "Angemeldet – PTZ-Steuerung bereit",
    "Size": "Größe",
    "Skip": "Überspringen",
    "Small": "Klein",
    "Source": "Quelle",
    "Start QuickProtect at Login?": "QuickProtect beim Anmelden starten?",
    "Startup": "Start",
    "Step 1 of 3": "Schritt 1 von 3",
    "Step 2 of 3": "Schritt 2 von 3",
    "Step 3 of 3": "Schritt 3 von 3",
    "Stream protocol": "Stream-Protokoll",
    "Stream unavailable": "Stream nicht verfügbar",
    "Test Connection": "Verbindung testen",
    "Theme": "Design",
    "Tilt down": "Nach unten neigen",
    "Tilt up": "Nach oben neigen",
    "To pan and tilt PTZ cameras, QuickProtect needs a local admin account. The Integration API key doesn't expose PTZ endpoints. You can skip this and add it later in Settings.": "Zum Schwenken und Neigen von PTZ-Kameras benötigt QuickProtect ein lokales Admin-Konto. Der Integrations-API-Schlüssel bietet keine PTZ-Endpunkte. Du kannst diesen Schritt überspringen und ihn später in den Einstellungen hinzufügen.",
    "Toggle QuickProtect": "QuickProtect umschalten",
    "Updates": "Updates",
    "Username": "Benutzername",
    "Version": "Version",
    "View License": "Lizenz anzeigen",
    "View fullscreen": "Vollbild anzeigen",
    "View on GitHub": "Auf GitHub ansehen",
    "View the project source and releases.": "Quellcode und Releases des Projekts ansehen.",
    "Welcome to\nQuickProtect.": "Willkommen bei\nQuickProtect.",
    "Within QuickProtect": "Innerhalb von QuickProtect",
    "You're all set.": "Alles bereit.",
    "Zoom in feed": "Im Feed zoomen",
    "back to popover": "zurück zum Popover",
    "exit fullscreen": "Vollbild beenden",
    "just now": "gerade eben",
    "v%@ available": "v%@ verfügbar",
    "© 2026 Christian Bartels · Released under the MIT License.": "© 2026 Christian Bartels · Veröffentlicht unter der MIT-Lizenz.",
    "⌘+scroll": "⌘+Scrollen",
}

# ---------------------------------------------------------------------------
# French (informal "tu")
# ---------------------------------------------------------------------------
fr = {
    "API Key": "Clé API",
    "About": "À propos",
    "All set": "Terminé",
    "App replacement failed: %@": "Échec du remplacement de l'app : %@",
    "Accent": "Accent",
    "Appearance": "Apparence",
    "Auto": "Auto",
    "Automatically start QuickProtect when you log in.": "Démarrer QuickProtect automatiquement à la connexion.",
    "Back": "Retour",
    "Back to grid (Esc)": "Retour à la grille (Échap)",
    "Cameras": "Caméras",
    "Can't reach controller": "Contrôleur injoignable",
    "Cancel": "Annuler",
    "Change": "Modifier",
    "Check for Updates": "Rechercher des mises à jour",
    "Checking…": "Recherche…",
    "Classic API credentials": "Identifiants de l'API classique",
    "Clear": "Effacer",
    "Clear search": "Effacer la recherche",
    "Click": "Clic",
    "Click the aperture icon in your menu bar to open the camera grid, or press your global shortcut.": "Clique sur l'icône d'ouverture dans la barre des menus pour ouvrir la grille des caméras, ou utilisez votre raccourci global.",
    "Connect": "Connexion",
    "Connect your controller": "Connectez votre contrôleur",
    "Connected": "Connecté",
    "Connected, but no cameras came back. Adopt one in the Protect app, then refresh.": "Connecté, mais aucune caméra trouvée. Adoptez-en une dans l'app Protect, puis actualisez.",
    "Connecting…": "Connexion…",
    "Connection": "Connexion",
    "Continue": "Continuer",
    "Controller": "Contrôleur",
    "Dark": "Sombre",
    "Disconnected": "Déconnecté",
    "Dismiss": "Ignorer",
    "Display fullscreen": "Afficher en plein écran",
    "Display the keyboard-shortcut hints and the on-screen PTZ pad when a camera is in focus.": "Afficher les rappels de raccourcis clavier et le pavé PTZ à l'écran lorsqu'une caméra est en mode focus.",
    "Double-click": "Double-clic",
    "Download failed: %@": "Échec du téléchargement : %@",
    "Enable": "Activer",
    "Enter your UniFi Protect controller's local IP and an API key from its settings.": "Saisissez l'IP locale de votre contrôleur UniFi Protect et une clé API depuis ses réglages.",
    "Esc": "Échap",
    "Exit / back": "Quitter / retour",
    "F  ·  Space": "F  ·  Espace",
    "Failed to mount the update DMG": "Impossible de monter le DMG de mise à jour",
    "Failed to save download: %@": "Échec de l'enregistrement du téléchargement : %@",
    "Fill frame": "Remplir le cadre",
    "Finish": "Terminer",
    "Fit to frame": "Ajuster au cadre",
    "Focus camera": "Focaliser la caméra",
    "Focus view": "Mode focus",
    "Fullscreen": "Plein écran",
    "Fullscreen (F)": "Plein écran (F)",
    "General": "Général",
    "Global": "Global",
    "Grid": "Grille",
    "Hide this camera": "Masquer cette caméra",
    "IP Address": "Adresse IP",
    "Install Update": "Installer la mise à jour",
    "Installed": "Installée",
    "Installing update…": "Installation de la mise à jour…",
    "Integration API key from controller settings": "Clé de l'API d'intégration depuis les réglages du contrôleur",
    "Invalid IP address or URL.": "Adresse IP ou URL non valide.",
    "Large": "Grand",
    "Last try: %@": "Dernier essai : %@",
    "Launch at login": "Lancer à la connexion",
    "Legal": "Mentions légales",
    "License": "Licence",
    "Light": "Clair",
    "Live UniFi Protect feeds, one click from your menu bar.": "Les flux UniFi Protect en direct, à un clic de votre barre des menus.",
    "Local IP of your UniFi Protect controller": "IP locale de votre contrôleur UniFi Protect",
    "Local admin account on the Protect controller.": "Compte administrateur local sur le contrôleur Protect.",
    "Login failed — check the username and password": "Échec de la connexion — vérifiez le nom d'utilisateur et le mot de passe",
    "Login failed — check username and password": "Échec de la connexion — vérifiez le nom d'utilisateur et le mot de passe",
    "Medium": "Moyen",
    "Menu-bar status app for UniFi Protect. Live camera feeds, one click away.": "App de barre des menus pour UniFi Protect. Les flux des caméras en direct, à portée de clic.",
    "No API key configured. Open Settings.": "Aucune clé API configurée. Ouvrez les réglages.",
    "No DMG download URL found": "Aucune URL de téléchargement DMG trouvée",
    "No IP address configured. Open Settings.": "Aucune adresse IP configurée. Ouvrez les réglages.",
    "No app bundle found in the DMG": "Aucune app trouvée dans le DMG",
    "No cameras discovered yet. Run Test Connection on the Connection tab.": "Aucune caméra détectée pour le moment. Lancez « Tester la connexion » dans l'onglet Connexion.",
    "No cameras yet": "Aucune caméra pour l'instant",
    "Not Now": "Plus tard",
    "Not configured": "Non configuré",
    "Not verified": "Non vérifié",
    "Offline": "Hors ligne",
    "Open Settings": "Ouvrir les réglages",
    "Open in Protect": "Ouvrir dans Protect",
    "PTZ (optional)": "PTZ (facultatif)",
    "PTZ · ARROW KEYS": "PTZ · TOUCHES FLÉCHÉES",
    "PTZ control (optional)": "Contrôle PTZ (facultatif)",
    "PTZ control uses the classic Protect API, which requires a local account. The Integration API (API Key) does not expose PTZ endpoints.": "Le contrôle PTZ utilise l'API Protect classique, qui nécessite un compte local. L'API d'intégration (clé API) n'expose pas de points de terminaison PTZ.",
    "Pan & tilt (PTZ)": "Panoramique et inclinaison (PTZ)",
    "Pan / tilt": "Panoramique / inclinaison",
    "Pan left": "Panoramique à gauche",
    "Pan right": "Panoramique à droite",
    "Password": "Mot de passe",
    "Press shortcut…": "Appuyez sur le raccourci…",
    "QuickProtect can start automatically when you log in so your cameras are always one click away.": "QuickProtect peut démarrer automatiquement à la connexion pour que vos caméras soient toujours à un clic.",
    "QuickProtect – Settings": "QuickProtect – Réglages",
    "Quit QuickProtect": "Quitter QuickProtect",
    "RTSP · no media": "RTSP · aucun média",
    "Reconnect": "Reconnecter",
    "Refresh": "Actualiser",
    "Refresh cameras": "Actualiser les caméras",
    "Reset size to Auto": "Réinitialiser la taille sur Auto",
    "Retry": "Réessayer",
    "Search cameras": "Rechercher des caméras",
    "Settings": "Réglages",
    "Settings…": "Réglages…",
    "Shortcuts": "Raccourcis",
    "Show or hide the camera grid from anywhere.": "Affichez ou masquez la grille des caméras depuis n'importe où.",
    "Show overlay controls": "Afficher les commandes en surimpression",
    "Signed in · PTZ control ready": "Connecté · contrôle PTZ prêt",
    "Signed in — PTZ control ready": "Connecté — contrôle PTZ prêt",
    "Size": "Taille",
    "Skip": "Ignorer",
    "Small": "Petit",
    "Source": "Code source",
    "Start QuickProtect at Login?": "Démarrer QuickProtect à la connexion ?",
    "Startup": "Démarrage",
    "Step 1 of 3": "Étape 1 sur 3",
    "Step 2 of 3": "Étape 2 sur 3",
    "Step 3 of 3": "Étape 3 sur 3",
    "Stream protocol": "Protocole de flux",
    "Stream unavailable": "Flux indisponible",
    "Test Connection": "Tester la connexion",
    "Theme": "Thème",
    "Tilt down": "Incliner vers le bas",
    "Tilt up": "Incliner vers le haut",
    "To pan and tilt PTZ cameras, QuickProtect needs a local admin account. The Integration API key doesn't expose PTZ endpoints. You can skip this and add it later in Settings.": "Pour effectuer un panoramique et incliner les caméras PTZ, QuickProtect a besoin d'un compte administrateur local. La clé de l'API d'intégration n'expose pas de points de terminaison PTZ. Vous pouvez ignorer cette étape et l'ajouter plus tard dans les réglages.",
    "Toggle QuickProtect": "Afficher/masquer QuickProtect",
    "Updates": "Mises à jour",
    "Username": "Nom d'utilisateur",
    "Version": "Version",
    "View License": "Voir la licence",
    "View fullscreen": "Afficher en plein écran",
    "View on GitHub": "Voir sur GitHub",
    "View the project source and releases.": "Voir le code source du projet et les versions.",
    "Welcome to\nQuickProtect.": "Bienvenue dans\nQuickProtect.",
    "Within QuickProtect": "Dans QuickProtect",
    "You're all set.": "Tout est prêt.",
    "Zoom in feed": "Zoomer dans le flux",
    "back to popover": "retour à la fenêtre",
    "exit fullscreen": "quitter le plein écran",
    "just now": "à l'instant",
    "v%@ available": "v%@ disponible",
    "© 2026 Christian Bartels · Released under the MIT License.": "© 2026 Christian Bartels · Distribué sous licence MIT.",
    "⌘+scroll": "⌘+défilement",
}

# ---------------------------------------------------------------------------
# Spanish (informal "tú")
# ---------------------------------------------------------------------------
es = {
    "API Key": "Clave API",
    "About": "Acerca de",
    "All set": "Listo",
    "App replacement failed: %@": "Error al reemplazar la app: %@",
    "Accent": "Acento",
    "Appearance": "Apariencia",
    "Auto": "Auto",
    "Automatically start QuickProtect when you log in.": "Iniciar QuickProtect automáticamente al iniciar sesión.",
    "Back": "Atrás",
    "Back to grid (Esc)": "Volver a la cuadrícula (Esc)",
    "Cameras": "Cámaras",
    "Can't reach controller": "No se puede conectar con el controlador",
    "Cancel": "Cancelar",
    "Change": "Cambiar",
    "Check for Updates": "Buscar actualizaciones",
    "Checking…": "Buscando…",
    "Classic API credentials": "Credenciales de la API clásica",
    "Clear": "Borrar",
    "Clear search": "Borrar búsqueda",
    "Click": "Clic",
    "Click the aperture icon in your menu bar to open the camera grid, or press your global shortcut.": "Haz clic en el icono de apertura en la barra de menús para abrir la cuadrícula de cámaras, o pulsa tu atajo global.",
    "Connect": "Conectar",
    "Connect your controller": "Conecta tu controlador",
    "Connected": "Conectado",
    "Connected, but no cameras came back. Adopt one in the Protect app, then refresh.": "Conectado, pero no se encontraron cámaras. Adopta una en la app Protect y luego actualiza.",
    "Connecting…": "Conectando…",
    "Connection": "Conexión",
    "Continue": "Continuar",
    "Controller": "Controlador",
    "Dark": "Oscuro",
    "Disconnected": "Desconectado",
    "Dismiss": "Descartar",
    "Display fullscreen": "Mostrar en pantalla completa",
    "Display the keyboard-shortcut hints and the on-screen PTZ pad when a camera is in focus.": "Mostrar las indicaciones de atajos de teclado y el panel PTZ en pantalla cuando una cámara está en modo enfoque.",
    "Double-click": "Doble clic",
    "Download failed: %@": "Error en la descarga: %@",
    "Enable": "Activar",
    "Enter your UniFi Protect controller's local IP and an API key from its settings.": "Introduce la IP local de tu controlador UniFi Protect y una clave API desde sus ajustes.",
    "Esc": "Esc",
    "Exit / back": "Salir / atrás",
    "F  ·  Space": "F  ·  Espacio",
    "Failed to mount the update DMG": "No se pudo montar el DMG de actualización",
    "Failed to save download: %@": "No se pudo guardar la descarga: %@",
    "Fill frame": "Llenar el cuadro",
    "Finish": "Finalizar",
    "Fit to frame": "Ajustar al cuadro",
    "Focus camera": "Enfocar cámara",
    "Focus view": "Vista de enfoque",
    "Fullscreen": "Pantalla completa",
    "Fullscreen (F)": "Pantalla completa (F)",
    "General": "General",
    "Global": "Global",
    "Grid": "Cuadrícula",
    "Hide this camera": "Ocultar esta cámara",
    "IP Address": "Dirección IP",
    "Install Update": "Instalar actualización",
    "Installed": "Instalada",
    "Installing update…": "Instalando actualización…",
    "Integration API key from controller settings": "Clave de la API de integración desde los ajustes del controlador",
    "Invalid IP address or URL.": "Dirección IP o URL no válida.",
    "Large": "Grande",
    "Last try: %@": "Último intento: %@",
    "Launch at login": "Abrir al iniciar sesión",
    "Legal": "Legal",
    "License": "Licencia",
    "Light": "Claro",
    "Live UniFi Protect feeds, one click from your menu bar.": "Transmisiones UniFi Protect en directo, a un clic desde tu barra de menús.",
    "Local IP of your UniFi Protect controller": "IP local de tu controlador UniFi Protect",
    "Local admin account on the Protect controller.": "Cuenta de administrador local en el controlador Protect.",
    "Login failed — check the username and password": "Error de inicio de sesión — comprueba el usuario y la contraseña",
    "Login failed — check username and password": "Error de inicio de sesión — comprueba el usuario y la contraseña",
    "Medium": "Mediano",
    "Menu-bar status app for UniFi Protect. Live camera feeds, one click away.": "App de barra de menús para UniFi Protect. Transmisiones de cámaras en directo, a un solo clic.",
    "No API key configured. Open Settings.": "No hay clave API configurada. Abre los ajustes.",
    "No DMG download URL found": "No se encontró ninguna URL de descarga del DMG",
    "No IP address configured. Open Settings.": "No hay dirección IP configurada. Abre los ajustes.",
    "No app bundle found in the DMG": "No se encontró ninguna app en el DMG",
    "No cameras discovered yet. Run Test Connection on the Connection tab.": "Aún no se han detectado cámaras. Ejecuta «Probar conexión» en la pestaña Conexión.",
    "No cameras yet": "Aún no hay cámaras",
    "Not Now": "Ahora no",
    "Not configured": "Sin configurar",
    "Not verified": "Sin verificar",
    "Offline": "Sin conexión",
    "Open Settings": "Abrir ajustes",
    "Open in Protect": "Abrir en Protect",
    "PTZ (optional)": "PTZ (opcional)",
    "PTZ · ARROW KEYS": "PTZ · TECLAS DE FLECHA",
    "PTZ control (optional)": "Control PTZ (opcional)",
    "PTZ control uses the classic Protect API, which requires a local account. The Integration API (API Key) does not expose PTZ endpoints.": "El control PTZ usa la API clásica de Protect, que requiere una cuenta local. La API de integración (clave API) no expone endpoints PTZ.",
    "Pan & tilt (PTZ)": "Giro e inclinación (PTZ)",
    "Pan / tilt": "Giro / inclinación",
    "Pan left": "Girar a la izquierda",
    "Pan right": "Girar a la derecha",
    "Password": "Contraseña",
    "Press shortcut…": "Pulsa el atajo…",
    "QuickProtect can start automatically when you log in so your cameras are always one click away.": "QuickProtect puede iniciarse automáticamente al iniciar sesión para que tus cámaras estén siempre a un clic.",
    "QuickProtect – Settings": "QuickProtect – Ajustes",
    "Quit QuickProtect": "Salir de QuickProtect",
    "RTSP · no media": "RTSP · sin contenido",
    "Reconnect": "Reconectar",
    "Refresh": "Actualizar",
    "Refresh cameras": "Actualizar cámaras",
    "Reset size to Auto": "Restablecer tamaño a Auto",
    "Retry": "Reintentar",
    "Search cameras": "Buscar cámaras",
    "Settings": "Ajustes",
    "Settings…": "Ajustes…",
    "Shortcuts": "Atajos",
    "Show or hide the camera grid from anywhere.": "Muestra u oculta la cuadrícula de cámaras desde cualquier lugar.",
    "Show overlay controls": "Mostrar controles superpuestos",
    "Signed in · PTZ control ready": "Sesión iniciada · control PTZ listo",
    "Signed in — PTZ control ready": "Sesión iniciada — control PTZ listo",
    "Size": "Tamaño",
    "Skip": "Omitir",
    "Small": "Pequeño",
    "Source": "Código fuente",
    "Start QuickProtect at Login?": "¿Iniciar QuickProtect al iniciar sesión?",
    "Startup": "Inicio",
    "Step 1 of 3": "Paso 1 de 3",
    "Step 2 of 3": "Paso 2 de 3",
    "Step 3 of 3": "Paso 3 de 3",
    "Stream protocol": "Protocolo de transmisión",
    "Stream unavailable": "Transmisión no disponible",
    "Test Connection": "Probar conexión",
    "Theme": "Tema",
    "Tilt down": "Inclinar hacia abajo",
    "Tilt up": "Inclinar hacia arriba",
    "To pan and tilt PTZ cameras, QuickProtect needs a local admin account. The Integration API key doesn't expose PTZ endpoints. You can skip this and add it later in Settings.": "Para girar e inclinar las cámaras PTZ, QuickProtect necesita una cuenta de administrador local. La clave de la API de integración no expone endpoints PTZ. Puedes omitir esto y añadirlo más tarde en los ajustes.",
    "Toggle QuickProtect": "Mostrar/ocultar QuickProtect",
    "Updates": "Actualizaciones",
    "Username": "Usuario",
    "Version": "Versión",
    "View License": "Ver licencia",
    "View fullscreen": "Ver en pantalla completa",
    "View on GitHub": "Ver en GitHub",
    "View the project source and releases.": "Ver el código fuente del proyecto y las versiones.",
    "Welcome to\nQuickProtect.": "Te damos la bienvenida a\nQuickProtect.",
    "Within QuickProtect": "Dentro de QuickProtect",
    "You're all set.": "Todo listo.",
    "Zoom in feed": "Acercar en la transmisión",
    "back to popover": "volver a la ventana",
    "exit fullscreen": "salir de pantalla completa",
    "just now": "ahora mismo",
    "v%@ available": "v%@ disponible",
    "© 2026 Christian Bartels · Released under the MIT License.": "© 2026 Christian Bartels · Publicado bajo la licencia MIT.",
    "⌘+scroll": "⌘+desplazamiento",
}

# ---------------------------------------------------------------------------
# Dutch (informal "je")
# ---------------------------------------------------------------------------
nl = {
    "API Key": "API-sleutel",
    "About": "Over",
    "All set": "Klaar",
    "App replacement failed: %@": "Vervangen van app mislukt: %@",
    "Accent": "Accent",
    "Appearance": "Weergave",
    "Auto": "Auto",
    "Automatically start QuickProtect when you log in.": "Start QuickProtect automatisch wanneer je inlogt.",
    "Back": "Terug",
    "Back to grid (Esc)": "Terug naar raster (Esc)",
    "Cameras": "Camera's",
    "Can't reach controller": "Controller niet bereikbaar",
    "Cancel": "Annuleer",
    "Change": "Wijzig",
    "Check for Updates": "Zoek naar updates",
    "Checking…": "Bezig met zoeken…",
    "Classic API credentials": "Inloggegevens klassieke API",
    "Clear": "Wis",
    "Clear search": "Zoekopdracht wissen",
    "Click": "Klik",
    "Click the aperture icon in your menu bar to open the camera grid, or press your global shortcut.": "Klik op het diafragmasymbool in de menubalk om het cameraraster te openen, of gebruik je globale sneltoets.",
    "Connect": "Verbinden",
    "Connect your controller": "Verbind je controller",
    "Connected": "Verbonden",
    "Connected, but no cameras came back. Adopt one in the Protect app, then refresh.": "Verbonden, maar geen camera's gevonden. Adopteer er een in de Protect-app en vernieuw daarna.",
    "Connecting…": "Verbinden…",
    "Connection": "Verbinding",
    "Continue": "Ga door",
    "Controller": "Controller",
    "Dark": "Donker",
    "Disconnected": "Verbroken",
    "Dismiss": "Negeer",
    "Display fullscreen": "Toon op volledig scherm",
    "Display the keyboard-shortcut hints and the on-screen PTZ pad when a camera is in focus.": "Toon de sneltoetshints en het PTZ-bedieningspaneel op het scherm wanneer een camera in focus is.",
    "Double-click": "Dubbelklik",
    "Download failed: %@": "Download mislukt: %@",
    "Enable": "Inschakelen",
    "Enter your UniFi Protect controller's local IP and an API key from its settings.": "Voer het lokale IP-adres van je UniFi Protect-controller en een API-sleutel uit de instellingen in.",
    "Esc": "Esc",
    "Exit / back": "Sluiten / terug",
    "F  ·  Space": "F  ·  Spatie",
    "Failed to mount the update DMG": "Kan de update-DMG niet koppelen",
    "Failed to save download: %@": "Kan download niet opslaan: %@",
    "Fill frame": "Beeld vullen",
    "Finish": "Voltooi",
    "Fit to frame": "Passend maken",
    "Focus camera": "Camera focussen",
    "Focus view": "Focusweergave",
    "Fullscreen": "Volledig scherm",
    "Fullscreen (F)": "Volledig scherm (F)",
    "General": "Algemeen",
    "Global": "Globaal",
    "Grid": "Raster",
    "Hide this camera": "Verberg deze camera",
    "IP Address": "IP-adres",
    "Install Update": "Installeer update",
    "Installed": "Geïnstalleerd",
    "Installing update…": "Update wordt geïnstalleerd…",
    "Integration API key from controller settings": "Integratie-API-sleutel uit de controllerinstellingen",
    "Invalid IP address or URL.": "Ongeldig IP-adres of URL.",
    "Large": "Groot",
    "Last try: %@": "Laatste poging: %@",
    "Launch at login": "Start bij inloggen",
    "Legal": "Juridisch",
    "License": "Licentie",
    "Light": "Licht",
    "Live UniFi Protect feeds, one click from your menu bar.": "Live UniFi Protect-feeds, één klik vanaf je menubalk.",
    "Local IP of your UniFi Protect controller": "Lokaal IP-adres van je UniFi Protect-controller",
    "Local admin account on the Protect controller.": "Lokaal beheerdersaccount op de Protect-controller.",
    "Login failed — check the username and password": "Inloggen mislukt — controleer gebruikersnaam en wachtwoord",
    "Login failed — check username and password": "Inloggen mislukt — controleer gebruikersnaam en wachtwoord",
    "Medium": "Gemiddeld",
    "Menu-bar status app for UniFi Protect. Live camera feeds, one click away.": "Menubalk-app voor UniFi Protect. Live camerabeelden, één klik verwijderd.",
    "No API key configured. Open Settings.": "Geen API-sleutel ingesteld. Open de instellingen.",
    "No DMG download URL found": "Geen DMG-download-URL gevonden",
    "No IP address configured. Open Settings.": "Geen IP-adres ingesteld. Open de instellingen.",
    "No app bundle found in the DMG": "Geen app gevonden in de DMG",
    "No cameras discovered yet. Run Test Connection on the Connection tab.": "Nog geen camera's gevonden. Voer „Verbinding testen“ uit op het tabblad Verbinding.",
    "No cameras yet": "Nog geen camera's",
    "Not Now": "Niet nu",
    "Not configured": "Niet ingesteld",
    "Not verified": "Niet geverifieerd",
    "Offline": "Offline",
    "Open Settings": "Open instellingen",
    "Open in Protect": "Open in Protect",
    "PTZ (optional)": "PTZ (optioneel)",
    "PTZ · ARROW KEYS": "PTZ · PIJLTOETSEN",
    "PTZ control (optional)": "PTZ-bediening (optioneel)",
    "PTZ control uses the classic Protect API, which requires a local account. The Integration API (API Key) does not expose PTZ endpoints.": "PTZ-bediening gebruikt de klassieke Protect-API, waarvoor een lokaal account nodig is. De integratie-API (API-sleutel) biedt geen PTZ-endpoints.",
    "Pan & tilt (PTZ)": "Pannen en kantelen (PTZ)",
    "Pan / tilt": "Pannen / kantelen",
    "Pan left": "Naar links pannen",
    "Pan right": "Naar rechts pannen",
    "Password": "Wachtwoord",
    "Press shortcut…": "Druk op de sneltoets…",
    "QuickProtect can start automatically when you log in so your cameras are always one click away.": "QuickProtect kan automatisch starten wanneer je inlogt, zodat je camera's altijd één klik verwijderd zijn.",
    "QuickProtect – Settings": "QuickProtect – Instellingen",
    "Quit QuickProtect": "Stop QuickProtect",
    "RTSP · no media": "RTSP · geen media",
    "Reconnect": "Opnieuw verbinden",
    "Refresh": "Vernieuw",
    "Refresh cameras": "Camera's vernieuwen",
    "Reset size to Auto": "Formaat terugzetten op Auto",
    "Retry": "Opnieuw",
    "Search cameras": "Zoek camera's",
    "Settings": "Instellingen",
    "Settings…": "Instellingen…",
    "Shortcuts": "Sneltoetsen",
    "Show or hide the camera grid from anywhere.": "Toon of verberg het cameraraster vanaf elke plek.",
    "Show overlay controls": "Toon overlay-bediening",
    "Signed in · PTZ control ready": "Ingelogd · PTZ-bediening gereed",
    "Signed in — PTZ control ready": "Ingelogd — PTZ-bediening gereed",
    "Size": "Formaat",
    "Skip": "Sla over",
    "Small": "Klein",
    "Source": "Broncode",
    "Start QuickProtect at Login?": "QuickProtect starten bij inloggen?",
    "Startup": "Opstarten",
    "Step 1 of 3": "Stap 1 van 3",
    "Step 2 of 3": "Stap 2 van 3",
    "Step 3 of 3": "Stap 3 van 3",
    "Stream protocol": "Streamprotocol",
    "Stream unavailable": "Stream niet beschikbaar",
    "Test Connection": "Verbinding testen",
    "Theme": "Thema",
    "Tilt down": "Omlaag kantelen",
    "Tilt up": "Omhoog kantelen",
    "To pan and tilt PTZ cameras, QuickProtect needs a local admin account. The Integration API key doesn't expose PTZ endpoints. You can skip this and add it later in Settings.": "Om PTZ-camera's te pannen en te kantelen heeft QuickProtect een lokaal beheerdersaccount nodig. De integratie-API-sleutel biedt geen PTZ-endpoints. Je kunt dit overslaan en het later in de instellingen toevoegen.",
    "Toggle QuickProtect": "QuickProtect tonen/verbergen",
    "Updates": "Updates",
    "Username": "Gebruikersnaam",
    "Version": "Versie",
    "View License": "Bekijk licentie",
    "View fullscreen": "Toon op volledig scherm",
    "View on GitHub": "Bekijk op GitHub",
    "View the project source and releases.": "Bekijk de broncode en releases van het project.",
    "Welcome to\nQuickProtect.": "Welkom bij\nQuickProtect.",
    "Within QuickProtect": "Binnen QuickProtect",
    "You're all set.": "Alles is klaar.",
    "Zoom in feed": "Inzoomen op beeld",
    "back to popover": "terug naar pop-over",
    "exit fullscreen": "volledig scherm sluiten",
    "just now": "zojuist",
    "v%@ available": "v%@ beschikbaar",
    "© 2026 Christian Bartels · Released under the MIT License.": "© 2026 Christian Bartels · Uitgebracht onder de MIT-licentie.",
    "⌘+scroll": "⌘+scrollen",
}

# ---------------------------------------------------------------------------
# Italian (informal "tu")
# ---------------------------------------------------------------------------
it = {
    "API Key": "Chiave API",
    "About": "Informazioni",
    "All set": "Pronto",
    "App replacement failed: %@": "Sostituzione dell'app non riuscita: %@",
    "Accent": "Accento",
    "Appearance": "Aspetto",
    "Auto": "Auto",
    "Automatically start QuickProtect when you log in.": "Avvia QuickProtect automaticamente all'accesso.",
    "Back": "Indietro",
    "Back to grid (Esc)": "Torna alla griglia (Esc)",
    "Cameras": "Telecamere",
    "Can't reach controller": "Controller non raggiungibile",
    "Cancel": "Annulla",
    "Change": "Modifica",
    "Check for Updates": "Verifica aggiornamenti",
    "Checking…": "Verifica…",
    "Classic API credentials": "Credenziali API classica",
    "Clear": "Cancella",
    "Clear search": "Cancella ricerca",
    "Click": "Clic",
    "Click the aperture icon in your menu bar to open the camera grid, or press your global shortcut.": "Fai clic sull'icona del diaframma nella barra dei menu per aprire la griglia delle telecamere, oppure usa la tua scorciatoia globale.",
    "Connect": "Connetti",
    "Connect your controller": "Connetti il tuo controller",
    "Connected": "Connesso",
    "Connected, but no cameras came back. Adopt one in the Protect app, then refresh.": "Connesso, ma nessuna telecamera trovata. Adottane una nell'app Protect, poi aggiorna.",
    "Connecting…": "Connessione…",
    "Connection": "Connessione",
    "Continue": "Continua",
    "Controller": "Controller",
    "Dark": "Scuro",
    "Disconnected": "Disconnesso",
    "Dismiss": "Ignora",
    "Display fullscreen": "Mostra a schermo intero",
    "Display the keyboard-shortcut hints and the on-screen PTZ pad when a camera is in focus.": "Mostra i suggerimenti delle scorciatoie da tastiera e il pad PTZ sullo schermo quando una telecamera è in primo piano.",
    "Double-click": "Doppio clic",
    "Download failed: %@": "Download non riuscito: %@",
    "Enable": "Attiva",
    "Enter your UniFi Protect controller's local IP and an API key from its settings.": "Inserisci l'IP locale del tuo controller UniFi Protect e una chiave API dalle sue impostazioni.",
    "Esc": "Esc",
    "Exit / back": "Esci / indietro",
    "F  ·  Space": "F  ·  Spazio",
    "Failed to mount the update DMG": "Impossibile montare il DMG di aggiornamento",
    "Failed to save download: %@": "Impossibile salvare il download: %@",
    "Fill frame": "Riempi il riquadro",
    "Finish": "Fine",
    "Fit to frame": "Adatta al riquadro",
    "Focus camera": "Metti a fuoco la telecamera",
    "Focus view": "Vista a fuoco",
    "Fullscreen": "Schermo intero",
    "Fullscreen (F)": "Schermo intero (F)",
    "General": "Generale",
    "Global": "Globale",
    "Grid": "Griglia",
    "Hide this camera": "Nascondi questa telecamera",
    "IP Address": "Indirizzo IP",
    "Install Update": "Installa aggiornamento",
    "Installed": "Installata",
    "Installing update…": "Installazione aggiornamento…",
    "Integration API key from controller settings": "Chiave dell'API di integrazione dalle impostazioni del controller",
    "Invalid IP address or URL.": "Indirizzo IP o URL non valido.",
    "Large": "Grande",
    "Last try: %@": "Ultimo tentativo: %@",
    "Launch at login": "Avvia all'accesso",
    "Legal": "Note legali",
    "License": "Licenza",
    "Light": "Chiaro",
    "Live UniFi Protect feeds, one click from your menu bar.": "Feed UniFi Protect in diretta, a un clic dalla barra dei menu.",
    "Local IP of your UniFi Protect controller": "IP locale del tuo controller UniFi Protect",
    "Local admin account on the Protect controller.": "Account amministratore locale sul controller Protect.",
    "Login failed — check the username and password": "Accesso non riuscito — controlla nome utente e password",
    "Login failed — check username and password": "Accesso non riuscito — controlla nome utente e password",
    "Medium": "Medio",
    "Menu-bar status app for UniFi Protect. Live camera feeds, one click away.": "App per la barra dei menu per UniFi Protect. Feed delle telecamere in diretta, a portata di clic.",
    "No API key configured. Open Settings.": "Nessuna chiave API configurata. Apri le impostazioni.",
    "No DMG download URL found": "Nessun URL di download del DMG trovato",
    "No IP address configured. Open Settings.": "Nessun indirizzo IP configurato. Apri le impostazioni.",
    "No app bundle found in the DMG": "Nessuna app trovata nel DMG",
    "No cameras discovered yet. Run Test Connection on the Connection tab.": "Nessuna telecamera rilevata finora. Esegui «Prova connessione» nella scheda Connessione.",
    "No cameras yet": "Ancora nessuna telecamera",
    "Not Now": "Non ora",
    "Not configured": "Non configurato",
    "Not verified": "Non verificato",
    "Offline": "Offline",
    "Open Settings": "Apri impostazioni",
    "Open in Protect": "Apri in Protect",
    "PTZ (optional)": "PTZ (opzionale)",
    "PTZ · ARROW KEYS": "PTZ · TASTI FRECCIA",
    "PTZ control (optional)": "Controllo PTZ (opzionale)",
    "PTZ control uses the classic Protect API, which requires a local account. The Integration API (API Key) does not expose PTZ endpoints.": "Il controllo PTZ usa l'API Protect classica, che richiede un account locale. L'API di integrazione (chiave API) non espone endpoint PTZ.",
    "Pan & tilt (PTZ)": "Brandeggio e inclinazione (PTZ)",
    "Pan / tilt": "Brandeggio / inclinazione",
    "Pan left": "Brandeggio a sinistra",
    "Pan right": "Brandeggio a destra",
    "Password": "Password",
    "Press shortcut…": "Premi la scorciatoia…",
    "QuickProtect can start automatically when you log in so your cameras are always one click away.": "QuickProtect può avviarsi automaticamente all'accesso così le tue telecamere sono sempre a un clic.",
    "QuickProtect – Settings": "QuickProtect – Impostazioni",
    "Quit QuickProtect": "Esci da QuickProtect",
    "RTSP · no media": "RTSP · nessun contenuto",
    "Reconnect": "Riconnetti",
    "Refresh": "Aggiorna",
    "Refresh cameras": "Aggiorna telecamere",
    "Reset size to Auto": "Reimposta dimensione su Auto",
    "Retry": "Riprova",
    "Search cameras": "Cerca telecamere",
    "Settings": "Impostazioni",
    "Settings…": "Impostazioni…",
    "Shortcuts": "Scorciatoie",
    "Show or hide the camera grid from anywhere.": "Mostra o nasconde la griglia delle telecamere da qualsiasi punto.",
    "Show overlay controls": "Mostra i controlli in sovrimpressione",
    "Signed in · PTZ control ready": "Accesso effettuato · controllo PTZ pronto",
    "Signed in — PTZ control ready": "Accesso effettuato — controllo PTZ pronto",
    "Size": "Dimensione",
    "Skip": "Salta",
    "Small": "Piccolo",
    "Source": "Codice sorgente",
    "Start QuickProtect at Login?": "Avviare QuickProtect all'accesso?",
    "Startup": "Avvio",
    "Step 1 of 3": "Passaggio 1 di 3",
    "Step 2 of 3": "Passaggio 2 di 3",
    "Step 3 of 3": "Passaggio 3 di 3",
    "Stream protocol": "Protocollo di streaming",
    "Stream unavailable": "Stream non disponibile",
    "Test Connection": "Prova connessione",
    "Theme": "Tema",
    "Tilt down": "Inclina verso il basso",
    "Tilt up": "Inclina verso l'alto",
    "To pan and tilt PTZ cameras, QuickProtect needs a local admin account. The Integration API key doesn't expose PTZ endpoints. You can skip this and add it later in Settings.": "Per il brandeggio e l'inclinazione delle telecamere PTZ, QuickProtect ha bisogno di un account amministratore locale. La chiave dell'API di integrazione non espone endpoint PTZ. Puoi saltare questo passaggio e aggiungerlo più tardi nelle impostazioni.",
    "Toggle QuickProtect": "Mostra/nascondi QuickProtect",
    "Updates": "Aggiornamenti",
    "Username": "Nome utente",
    "Version": "Versione",
    "View License": "Visualizza licenza",
    "View fullscreen": "Visualizza a schermo intero",
    "View on GitHub": "Visualizza su GitHub",
    "View the project source and releases.": "Visualizza il codice sorgente del progetto e le release.",
    "Welcome to\nQuickProtect.": "Ti diamo il benvenuto in\nQuickProtect.",
    "Within QuickProtect": "In QuickProtect",
    "You're all set.": "Tutto pronto.",
    "Zoom in feed": "Zoom nel feed",
    "back to popover": "torna al popover",
    "exit fullscreen": "esci da schermo intero",
    "just now": "proprio ora",
    "v%@ available": "v%@ disponibile",
    "© 2026 Christian Bartels · Released under the MIT License.": "© 2026 Christian Bartels · Rilasciato sotto licenza MIT.",
    "⌘+scroll": "⌘+scorrimento",
}

# ---------------------------------------------------------------------------
# Brazilian Portuguese ("você")
# ---------------------------------------------------------------------------
pt_br = {
    "API Key": "Chave de API",
    "About": "Sobre",
    "All set": "Tudo pronto",
    "App replacement failed: %@": "Falha ao substituir o app: %@",
    "Accent": "Destaque",
    "Appearance": "Aparência",
    "Auto": "Auto",
    "Automatically start QuickProtect when you log in.": "Iniciar o QuickProtect automaticamente ao fazer login.",
    "Back": "Voltar",
    "Back to grid (Esc)": "Voltar à grade (Esc)",
    "Cameras": "Câmeras",
    "Can't reach controller": "Não foi possível conectar ao controlador",
    "Cancel": "Cancelar",
    "Change": "Alterar",
    "Check for Updates": "Buscar atualizações",
    "Checking…": "Verificando…",
    "Classic API credentials": "Credenciais da API clássica",
    "Clear": "Limpar",
    "Clear search": "Limpar busca",
    "Click": "Clique",
    "Click the aperture icon in your menu bar to open the camera grid, or press your global shortcut.": "Clique no ícone de abertura na barra de menus para abrir a grade de câmeras, ou use seu atalho global.",
    "Connect": "Conectar",
    "Connect your controller": "Conecte seu controlador",
    "Connected": "Conectado",
    "Connected, but no cameras came back. Adopt one in the Protect app, then refresh.": "Conectado, mas nenhuma câmera foi encontrada. Adote uma no app Protect e depois atualize.",
    "Connecting…": "Conectando…",
    "Connection": "Conexão",
    "Continue": "Continuar",
    "Controller": "Controlador",
    "Dark": "Escuro",
    "Disconnected": "Desconectado",
    "Dismiss": "Dispensar",
    "Display fullscreen": "Exibir em tela cheia",
    "Display the keyboard-shortcut hints and the on-screen PTZ pad when a camera is in focus.": "Mostrar as dicas de atalhos de teclado e o painel PTZ na tela quando uma câmera está em foco.",
    "Double-click": "Clique duplo",
    "Download failed: %@": "Falha no download: %@",
    "Enable": "Ativar",
    "Enter your UniFi Protect controller's local IP and an API key from its settings.": "Insira o IP local do seu controlador UniFi Protect e uma chave de API nas configurações dele.",
    "Esc": "Esc",
    "Exit / back": "Sair / voltar",
    "F  ·  Space": "F  ·  Espaço",
    "Failed to mount the update DMG": "Não foi possível montar o DMG de atualização",
    "Failed to save download: %@": "Não foi possível salvar o download: %@",
    "Fill frame": "Preencher o quadro",
    "Finish": "Concluir",
    "Fit to frame": "Ajustar ao quadro",
    "Focus camera": "Focar câmera",
    "Focus view": "Modo de foco",
    "Fullscreen": "Tela cheia",
    "Fullscreen (F)": "Tela cheia (F)",
    "General": "Geral",
    "Global": "Global",
    "Grid": "Grade",
    "Hide this camera": "Ocultar esta câmera",
    "IP Address": "Endereço IP",
    "Install Update": "Instalar atualização",
    "Installed": "Instalada",
    "Installing update…": "Instalando atualização…",
    "Integration API key from controller settings": "Chave da API de integração nas configurações do controlador",
    "Invalid IP address or URL.": "Endereço IP ou URL inválido.",
    "Large": "Grande",
    "Last try: %@": "Última tentativa: %@",
    "Launch at login": "Abrir ao fazer login",
    "Legal": "Jurídico",
    "License": "Licença",
    "Light": "Claro",
    "Live UniFi Protect feeds, one click from your menu bar.": "Transmissões UniFi Protect ao vivo, a um clique da sua barra de menus.",
    "Local IP of your UniFi Protect controller": "IP local do seu controlador UniFi Protect",
    "Local admin account on the Protect controller.": "Conta de administrador local no controlador Protect.",
    "Login failed — check the username and password": "Falha no login — verifique o usuário e a senha",
    "Login failed — check username and password": "Falha no login — verifique o usuário e a senha",
    "Medium": "Médio",
    "Menu-bar status app for UniFi Protect. Live camera feeds, one click away.": "App de barra de menus para UniFi Protect. Transmissões de câmeras ao vivo, a um clique de distância.",
    "No API key configured. Open Settings.": "Nenhuma chave de API configurada. Abra os ajustes.",
    "No DMG download URL found": "Nenhuma URL de download do DMG encontrada",
    "No IP address configured. Open Settings.": "Nenhum endereço IP configurado. Abra os ajustes.",
    "No app bundle found in the DMG": "Nenhum app encontrado no DMG",
    "No cameras discovered yet. Run Test Connection on the Connection tab.": "Nenhuma câmera detectada ainda. Execute «Testar conexão» na aba Conexão.",
    "No cameras yet": "Ainda não há câmeras",
    "Not Now": "Agora não",
    "Not configured": "Não configurado",
    "Not verified": "Não verificado",
    "Offline": "Offline",
    "Open Settings": "Abrir ajustes",
    "Open in Protect": "Abrir no Protect",
    "PTZ (optional)": "PTZ (opcional)",
    "PTZ · ARROW KEYS": "PTZ · TECLAS DE SETA",
    "PTZ control (optional)": "Controle PTZ (opcional)",
    "PTZ control uses the classic Protect API, which requires a local account. The Integration API (API Key) does not expose PTZ endpoints.": "O controle PTZ usa a API clássica do Protect, que exige uma conta local. A API de integração (chave de API) não expõe endpoints PTZ.",
    "Pan & tilt (PTZ)": "Pan e tilt (PTZ)",
    "Pan / tilt": "Pan / tilt",
    "Pan left": "Girar à esquerda",
    "Pan right": "Girar à direita",
    "Password": "Senha",
    "Press shortcut…": "Pressione o atalho…",
    "QuickProtect can start automatically when you log in so your cameras are always one click away.": "O QuickProtect pode iniciar automaticamente ao fazer login para que suas câmeras estejam sempre a um clique.",
    "QuickProtect – Settings": "QuickProtect – Ajustes",
    "Quit QuickProtect": "Encerrar o QuickProtect",
    "RTSP · no media": "RTSP · sem mídia",
    "Reconnect": "Reconectar",
    "Refresh": "Atualizar",
    "Refresh cameras": "Atualizar câmeras",
    "Reset size to Auto": "Redefinir tamanho para Auto",
    "Retry": "Tentar novamente",
    "Search cameras": "Buscar câmeras",
    "Settings": "Ajustes",
    "Settings…": "Ajustes…",
    "Shortcuts": "Atalhos",
    "Show or hide the camera grid from anywhere.": "Mostre ou oculte a grade de câmeras de qualquer lugar.",
    "Show overlay controls": "Mostrar controles sobrepostos",
    "Signed in · PTZ control ready": "Conectado · controle PTZ pronto",
    "Signed in — PTZ control ready": "Conectado — controle PTZ pronto",
    "Size": "Tamanho",
    "Skip": "Pular",
    "Small": "Pequeno",
    "Source": "Código-fonte",
    "Start QuickProtect at Login?": "Iniciar o QuickProtect ao fazer login?",
    "Startup": "Inicialização",
    "Step 1 of 3": "Etapa 1 de 3",
    "Step 2 of 3": "Etapa 2 de 3",
    "Step 3 of 3": "Etapa 3 de 3",
    "Stream protocol": "Protocolo de transmissão",
    "Stream unavailable": "Transmissão indisponível",
    "Test Connection": "Testar conexão",
    "Theme": "Tema",
    "Tilt down": "Inclinar para baixo",
    "Tilt up": "Inclinar para cima",
    "To pan and tilt PTZ cameras, QuickProtect needs a local admin account. The Integration API key doesn't expose PTZ endpoints. You can skip this and add it later in Settings.": "Para usar pan e tilt em câmeras PTZ, o QuickProtect precisa de uma conta de administrador local. A chave da API de integração não expõe endpoints PTZ. Você pode pular isto e adicionar depois nos ajustes.",
    "Toggle QuickProtect": "Mostrar/ocultar QuickProtect",
    "Updates": "Atualizações",
    "Username": "Usuário",
    "Version": "Versão",
    "View License": "Ver licença",
    "View fullscreen": "Ver em tela cheia",
    "View on GitHub": "Ver no GitHub",
    "View the project source and releases.": "Ver o código-fonte do projeto e as versões.",
    "Welcome to\nQuickProtect.": "Boas-vindas ao\nQuickProtect.",
    "Within QuickProtect": "Dentro do QuickProtect",
    "You're all set.": "Tudo pronto.",
    "Zoom in feed": "Ampliar na transmissão",
    "back to popover": "voltar à janela",
    "exit fullscreen": "sair da tela cheia",
    "just now": "agora mesmo",
    "v%@ available": "v%@ disponível",
    "© 2026 Christian Bartels · Released under the MIT License.": "© 2026 Christian Bartels · Lançado sob a licença MIT.",
    "⌘+scroll": "⌘+rolagem",
}

LANGS = {"de": de, "fr": fr, "es": es, "nl": nl, "it": it, "pt-BR": pt_br}

# ---------------------------------------------------------------------------
# Plurals — every key has (one, other) per language.
# ---------------------------------------------------------------------------
plurals = {
    "%lld streams": {
        "en": ("%lld stream", "%lld streams"),
        "de": ("%lld Stream", "%lld Streams"),
        "fr": ("%lld flux", "%lld flux"),
        "es": ("%lld transmisión", "%lld transmisiones"),
        "nl": ("%lld stream", "%lld streams"),
        "it": ("%lld stream", "%lld stream"),
        "pt-BR": ("%lld transmissão", "%lld transmissões"),
    },
    "%lld cameras detected.": {
        "en": ("%lld camera detected.", "%lld cameras detected."),
        "de": ("%lld Kamera erkannt.", "%lld Kameras erkannt."),
        "fr": ("%lld caméra détectée.", "%lld caméras détectées."),
        "es": ("%lld cámara detectada.", "%lld cámaras detectadas."),
        "nl": ("%lld camera gedetecteerd.", "%lld camera's gedetecteerd."),
        "it": ("%lld telecamera rilevata.", "%lld telecamere rilevate."),
        "pt-BR": ("%lld câmera detectada.", "%lld câmeras detectadas."),
    },
    "%lld seconds ago": {
        "en": ("%lld second ago", "%lld seconds ago"),
        "de": ("vor %lld Sekunde", "vor %lld Sekunden"),
        "fr": ("il y a %lld seconde", "il y a %lld secondes"),
        "es": ("hace %lld segundo", "hace %lld segundos"),
        "nl": ("%lld seconde geleden", "%lld seconden geleden"),
        "it": ("%lld secondo fa", "%lld secondi fa"),
        "pt-BR": ("há %lld segundo", "há %lld segundos"),
    },
    "%lld minutes ago": {
        "en": ("%lld minute ago", "%lld minutes ago"),
        "de": ("vor %lld Minute", "vor %lld Minuten"),
        "fr": ("il y a %lld minute", "il y a %lld minutes"),
        "es": ("hace %lld minuto", "hace %lld minutos"),
        "nl": ("%lld minuut geleden", "%lld minuten geleden"),
        "it": ("%lld minuto fa", "%lld minuti fa"),
        "pt-BR": ("há %lld minuto", "há %lld minutos"),
    },
    "Connected · %lld cameras found": {
        "en": ("Connected · %lld camera found", "Connected · %lld cameras found"),
        "de": ("Verbunden · %lld Kamera gefunden", "Verbunden · %lld Kameras gefunden"),
        "fr": ("Connecté · %lld caméra trouvée", "Connecté · %lld caméras trouvées"),
        "es": ("Conectado · %lld cámara encontrada", "Conectado · %lld cámaras encontradas"),
        "nl": ("Verbonden · %lld camera gevonden", "Verbonden · %lld camera's gevonden"),
        "it": ("Connesso · %lld telecamera trovata", "Connesso · %lld telecamere trovate"),
        "pt-BR": ("Conectado · %lld câmera encontrada", "Conectado · %lld câmeras encontradas"),
    },
    "Connected — %lld cameras found": {
        "en": ("Connected — %lld camera found", "Connected — %lld cameras found"),
        "de": ("Verbunden – %lld Kamera gefunden", "Verbunden – %lld Kameras gefunden"),
        "fr": ("Connecté — %lld caméra trouvée", "Connecté — %lld caméras trouvées"),
        "es": ("Conectado — %lld cámara encontrada", "Conectado — %lld cámaras encontradas"),
        "nl": ("Verbonden — %lld camera gevonden", "Verbonden — %lld camera's gevonden"),
        "it": ("Connesso — %lld telecamera trovata", "Connesso — %lld telecamere trovate"),
        "pt-BR": ("Conectado — %lld câmera encontrada", "Conectado — %lld câmeras encontradas"),
    },
}

# ---------------------------------------------------------------------------
# Parity check: every language must cover exactly the German key set.
# ---------------------------------------------------------------------------
ref = set(de)
problems = False
for code, d in LANGS.items():
    if code == "de":
        continue
    missing = ref - set(d)
    extra = set(d) - ref
    if missing or extra:
        problems = True
        print(f"[{code}] MISSING ({len(missing)}): {sorted(missing)}")
        print(f"[{code}] EXTRA ({len(extra)}): {sorted(extra)}")
if problems:
    print("Parity check FAILED — fix the dictionaries above.")
    sys.exit(1)
print("Parity check OK — all languages cover the full key set.")

# ---------------------------------------------------------------------------
# Build the catalog.
# ---------------------------------------------------------------------------
def unit(value):
    return {"stringUnit": {"state": "translated", "value": value}}

def plural_loc(one, other):
    return {"variations": {"plural": {"one": unit(one), "other": unit(other)}}}

strings = collections.OrderedDict()
for k in sorted(de):
    locs = {code: unit(d[k]) for code, d in LANGS.items()}
    strings[k] = {"extractionState": "manual", "localizations": locs}

for k in sorted(plurals):
    p = plurals[k]
    locs = {code: plural_loc(*vals) for code, vals in p.items()}
    strings[k] = {"extractionState": "manual", "localizations": locs}

catalog = {"sourceLanguage": "en", "strings": strings, "version": "1.0"}

_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out = os.path.join(_root, "QuickProtect", "Localizable.xcstrings")
with open(out, "w", encoding="utf-8") as f:
    json.dump(catalog, f, ensure_ascii=False, indent=2)
    f.write("\n")
print(f"Wrote {len(strings)} keys × {len(LANGS)} languages to {out}")
